#!/usr/bin/env bash
# Secrets Management Demo Script
# Demonstrates all secrets management features

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Demo working directory
DEMO_DIR="/tmp/nself-secrets-demo-$$"

# Utility functions
demo_header() {
  printf "\n${CYAN}═══════════════════════════════════════════════════════${NC}\n"
  printf "${CYAN}  %s${NC}\n" "$1"
  printf "${CYAN}═══════════════════════════════════════════════════════${NC}\n\n"
}

demo_step() {
  printf "${BLUE}➜${NC} ${YELLOW}%s${NC}\n" "$1"
}

demo_command() {
  printf "  ${GREEN}\$${NC} %s\n" "$1"
}

demo_output() {
  while IFS= read -r line; do
    printf "  %s\n" "$line"
  done
}

demo_success() {
  printf "${GREEN}✓${NC} %s\n" "$1"
}

demo_warning() {
  printf "${YELLOW}⚠${NC} %s\n" "$1"
}

demo_error() {
  printf "${RED}✗${NC} %s\n" "$1"
}

# Cleanup function
cleanup() {
  if [[ -d "$DEMO_DIR" ]]; then
    rm -rf "$DEMO_DIR"
  fi
}

trap cleanup EXIT

# Main demo
main() {
  demo_header "nself Secrets Management Demo"

  printf "This demo showcases the comprehensive secrets management system.\n"
  printf "All operations are performed in a temporary directory: %s\n" "$DEMO_DIR"
  printf "\n"
  printf "Press ENTER to continue..."
  read -r

  # Setup
  demo_header "1. Setup Demo Environment"
  demo_step "Creating temporary directory"
  demo_command "mkdir -p $DEMO_DIR && cd $DEMO_DIR"
  mkdir -p "$DEMO_DIR"
  cd "$DEMO_DIR"
  demo_success "Created demo directory"

  # Generate secrets
  demo_header "2. Generate Secrets"
  demo_step "Generating secure random secrets"
  demo_command "nself config secrets generate"

  # Create a mock secrets file for demo
  cat >.env.secrets <<'EOF'
# Production Secrets - NEVER COMMIT TO VERSION CONTROL
# Generated by nself on 2026-01-31

POSTGRES_PASSWORD=aB3kL9mP2xQ7vN4wY8zR1tS5uO6cF0dH
HASURA_GRAPHQL_ADMIN_SECRET=9f7e3d2c1b0a8e6f4d3c2b1a0e9f8d7c6b5a4e3d2c1b0a9f8e7d6c5b4a3e2d1c
JWT_SECRET=7c6b5a4e3d2c1b0a9f8e7d6c5b4a3e2d1c0b9a8f7e6d5c4b3a2e1d0c9b8a7f6e5
COOKIE_SECRET=4e3d2c1b0a9f8e7d6c5b4a3e2d1c0b9a
MINIO_ROOT_PASSWORD=kX9mP2vN4wY8zR1tS5uO6cF0dHaB3L7Q
REDIS_PASSWORD=pY8wZ1rT5sU6oC0fD9hA2bK3lM7nV4qX
GRAFANA_ADMIN_PASSWORD=gH6fI9jK2lM5nO8pQ1rT4sV7
EOF
  chmod 600 .env.secrets

  demo_output <<'OUTPUT'
# Production Secrets - NEVER COMMIT TO VERSION CONTROL
# Generated by nself on 2026-01-31

POSTGRES_PASSWORD=aB3kL9mP2xQ7vN4wY8zR1tS5uO6cF0dH
HASURA_GRAPHQL_ADMIN_SECRET=9f7e3d2c1b0a8e6f4d3c2b1a0e9f8d7c6b5a4e3d2c1b0a9f8e7d6c5b4a3e2d1c
JWT_SECRET=7c6b5a4e3d2c1b0a9f8e7d6c5b4a3e2d1c0b9a8f7e6d5c4b3a2e1d0c9b8a7f6e5
COOKIE_SECRET=4e3d2c1b0a9f8e7d6c5b4a3e2d1c0b9a
MINIO_ROOT_PASSWORD=kX9mP2vN4wY8zR1tS5uO6cF0dHaB3L7Q
REDIS_PASSWORD=pY8wZ1rT5sU6oC0fD9hA2bK3lM7nV4qX
GRAFANA_ADMIN_PASSWORD=gH6fI9jK2lM5nO8pQ1rT4sV7
OUTPUT

  demo_success "Secrets generated with secure random values"
  demo_success "File permissions set to 600 (owner read/write only)"

  # List secrets
  demo_header "3. List Secrets (Masked)"
  demo_step "Viewing all secrets with values masked"
  demo_command "nself config secrets list"

  demo_output <<'OUTPUT'
  POSTGRES_PASSWORD (32 chars)
  HASURA_GRAPHQL_ADMIN_SECRET (64 chars)
  JWT_SECRET (64 chars)
  COOKIE_SECRET (32 chars)
  MINIO_ROOT_PASSWORD (32 chars)
  REDIS_PASSWORD (32 chars)
  GRAFANA_ADMIN_PASSWORD (24 chars)
OUTPUT

  demo_success "All secrets listed (values hidden for security)"

  # Get specific secret
  demo_header "4. Get Specific Secret"
  demo_step "Retrieving a specific secret (masked by default)"
  demo_command "nself config secrets get POSTGRES_PASSWORD"

  demo_output <<'OUTPUT'
********
Use --reveal to show actual value
OUTPUT

  demo_step "Revealing actual value (use carefully!)"
  demo_command "nself config secrets get POSTGRES_PASSWORD --reveal"

  demo_output <<'OUTPUT'
aB3kL9mP2xQ7vN4wY8zR1tS5uO6cF0dH
OUTPUT

  demo_warning "Only use --reveal when absolutely necessary"

  # Validate secrets
  demo_header "5. Validate Secret Security"
  demo_step "Running comprehensive security validation"
  demo_command "nself config secrets validate"

  demo_output <<'OUTPUT'
Validating secrets in: .env.secrets

  ✓ POSTGRES_PASSWORD is set (32 chars)
  ✓ HASURA_GRAPHQL_ADMIN_SECRET is set (64 chars)
  ✓ JWT_SECRET is set (64 chars)
  ✓ COOKIE_SECRET is set (32 chars)
  ✓ MINIO_ROOT_PASSWORD is set (32 chars)
  ✓ REDIS_PASSWORD is set (32 chars)
  ✓ GRAFANA_ADMIN_PASSWORD is set (24 chars)

  ✓ File permissions are correct (600)

All secrets validated successfully
OUTPUT

  demo_success "All security checks passed"

  # Demonstrate weak secret detection
  demo_header "6. Weak Secret Detection"
  demo_step "Adding a weak password to demonstrate detection"
  echo "WEAK_PASSWORD=postgres123" >>.env.secrets

  demo_command "nself doctor"

  demo_output <<'OUTPUT'
⚠ Checking for weak or default secrets
  ❌ Detected 1 weak or default secret(s)

Weak secrets detected in .env.secrets!
Fix with: nself config secrets rotate --all
OUTPUT

  demo_error "Weak password detected automatically"
  demo_step "Removing weak password"
  sed -i.bak '/WEAK_PASSWORD=/d' .env.secrets
  demo_success "Weak password removed"

  # Rotate a secret
  demo_header "7. Secret Rotation"
  demo_step "Rotating a single secret"
  demo_command "nself config secrets rotate POSTGRES_PASSWORD"

  # Simulate rotation
  local new_password=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
  sed -i.bak "s/POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=$new_password/" .env.secrets
  cp .env.secrets ".env.secrets.backup-$(date +%Y%m%d-%H%M%S)"

  demo_output <<'OUTPUT'
Backup created: .env.secrets.backup-20260131-120000
Rotated secret: POSTGRES_PASSWORD
Remember to restart services to apply the new secret
OUTPUT

  demo_success "Secret rotated successfully"
  demo_success "Backup created automatically"

  # File permissions check
  demo_header "8. File Permissions Security"
  demo_step "Verifying file permissions"
  demo_command "ls -la .env.secrets"

  local perms=$(stat -c "%a" .env.secrets 2>/dev/null || stat -f "%OLp" .env.secrets 2>/dev/null)
  demo_output <<OUTPUT
-rw------- 1 user group 512 Jan 31 12:00 .env.secrets
Permissions: $perms
OUTPUT

  if [[ "$perms" == "600" ]]; then
    demo_success "File permissions are secure (600)"
  else
    demo_error "File permissions are incorrect"
  fi

  # Git safety
  demo_header "9. Git Safety Check"
  demo_step "Initializing git repository"
  git init -q

  demo_step "Creating .gitignore"
  echo ".env.secrets" >.gitignore

  demo_step "Checking if secrets are tracked"
  demo_command "git ls-files | grep .env.secrets"

  if git ls-files --error-unmatch .env.secrets >/dev/null 2>&1; then
    demo_error ".env.secrets IS TRACKED BY GIT - CRITICAL SECURITY ISSUE!"
  else
    demo_success ".env.secrets is not tracked by git"
  fi

  demo_step "Verifying .gitignore entry"
  if grep -q ".env.secrets" .gitignore; then
    demo_success ".env.secrets is in .gitignore"
  else
    demo_error ".env.secrets is NOT in .gitignore"
  fi

  # Encryption demo
  demo_header "10. Encrypt Secrets for Backup"
  demo_step "Encrypting secrets file"
  demo_command "nself config secrets encrypt .env.secrets"

  # Simulate encryption
  echo "demo-password" | openssl enc -aes-256-cbc -salt -pbkdf2 \
    -in .env.secrets -out .env.secrets.enc -pass stdin 2>/dev/null || true

  if [[ -f ".env.secrets.enc" ]]; then
    demo_output <<'OUTPUT'
Enter encryption password: ****
Encrypted secrets to: .env.secrets.enc
OUTPUT
    demo_success "Secrets encrypted successfully"
    demo_success "Safe to store in backups or cloud storage"
  fi

  # Summary
  demo_header "Demo Complete!"

  printf "This demo showcased:\n\n"
  printf "  ${GREEN}✓${NC} Secret generation with strong random values\n"
  printf "  ${GREEN}✓${NC} Listing and retrieving secrets (masked by default)\n"
  printf "  ${GREEN}✓${NC} Comprehensive security validation\n"
  printf "  ${GREEN}✓${NC} Weak password detection\n"
  printf "  ${GREEN}✓${NC} Secret rotation with automatic backups\n"
  printf "  ${GREEN}✓${NC} File permissions security (600)\n"
  printf "  ${GREEN}✓${NC} Git safety checks\n"
  printf "  ${GREEN}✓${NC} Encryption for secure backups\n"
  printf "\n"
  printf "For full documentation, see:\n"
  printf "  ${CYAN}.wiki/configuration/SECRETS-MANAGEMENT.md${NC}\n"
  printf "\n"
  printf "Available commands:\n"
  printf "  ${GREEN}nself config secrets --help${NC}\n"
  printf "  ${GREEN}nself doctor${NC}\n"
  printf "\n"
}

# Run demo
main "$@"
