package migration

import (
	"os"
	"path/filepath"
	"strings"
)

// LegacyArtifact describes a v1 artifact found in a project directory.
type LegacyArtifact struct {
	Path        string
	Description string
	Action      string // what the user should do
}

// DetectionThreshold is the minimum number of v0.9 artifacts required to
// trigger a hard failure in start/build/up. A single artifact causes a warning
// but proceeds; two or more artifacts block the command until migrated.
// This prevents false positives from projects that happen to share one artifact name.
const DetectionThreshold = 2

// CheckLegacyProject inspects the given directory and returns (count, artifact names).
// If count >= DetectionThreshold the caller should fail; if count == 1 it should warn.
// If count == 0 the project is clean. Reuses Detect() internals.
func CheckLegacyProject(projectDir string) (count int, names []string) {
	artifacts := Detect(projectDir)
	for _, a := range artifacts {
		names = append(names, a.Path)
	}
	return len(artifacts), names
}

// Detect scans the given directory for v0.9 artifacts.
// Returns an empty slice if no artifacts are found (clean v2 project or new project).
// No os.Exit calls — errors from file reads are treated as absent artifacts.
func Detect(projectDir string) []LegacyArtifact {
	var artifacts []LegacyArtifact

	// 1. docker-compose.yml — contains "# Generated by nself" but NOT "# nself v2"
	if a := detectComposeFile(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	// 2. .env — contains NSELF_VERSION=0. (v1 version format)
	if a := detectEnvFile(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	// 3. nginx/ directory — exists but does NOT have nginx/sites/ subdirectory
	if a := detectNginxDir(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	// 4. .nself/config — is a file (not a directory) — v1 config format
	if a := detectNselfConfig(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	// 5. nself.sh — exists at root — v1 bootstrap script
	if a := detectBootstrapScript(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	return artifacts
}

// detectComposeFile checks for a v1-generated docker-compose.yml.
func detectComposeFile(dir string) *LegacyArtifact {
	path := filepath.Join(dir, "docker-compose.yml")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	content := string(data)
	if strings.Contains(content, "# Generated by nself") && !strings.Contains(content, "# nself v2") {
		return &LegacyArtifact{
			Path:        "docker-compose.yml",
			Description: "v1-generated compose file",
			Action:      "run: nself migrate",
		}
	}
	return nil
}

// detectEnvFile checks for a v1 .env file with NSELF_VERSION=0.x.
func detectEnvFile(dir string) *LegacyArtifact {
	path := filepath.Join(dir, ".env")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	if strings.Contains(string(data), "NSELF_VERSION=0.") {
		return &LegacyArtifact{
			Path:        ".env",
			Description: "v1 environment file (NSELF_VERSION=0.x)",
			Action:      "run: nself migrate",
		}
	}
	return nil
}

// detectNginxDir checks for a v1 nginx/ directory (missing nginx/sites/ subdirectory).
func detectNginxDir(dir string) *LegacyArtifact {
	nginxDir := filepath.Join(dir, "nginx")
	info, err := os.Stat(nginxDir)
	if err != nil || !info.IsDir() {
		return nil
	}
	// v2 nginx always has a sites/ subdirectory
	sitesDir := filepath.Join(nginxDir, "sites")
	sitesInfo, err := os.Stat(sitesDir)
	if err != nil || !sitesInfo.IsDir() {
		return &LegacyArtifact{
			Path:        "nginx/",
			Description: "v1 nginx directory structure (missing nginx/sites/)",
			Action:      "run: nself migrate",
		}
	}
	return nil
}

// detectNselfConfig checks for a v1 .nself/config that is a file (not a directory).
func detectNselfConfig(dir string) *LegacyArtifact {
	configPath := filepath.Join(dir, ".nself", "config")
	info, err := os.Stat(configPath)
	if err != nil {
		return nil
	}
	// v1 stored config as a plain file; v2 uses it as a directory
	if !info.IsDir() {
		return &LegacyArtifact{
			Path:        ".nself/config",
			Description: "v1 config file (must be a directory in v2)",
			Action:      "run: nself migrate",
		}
	}
	return nil
}

// detectBootstrapScript checks for the v1 nself.sh bootstrap script.
func detectBootstrapScript(dir string) *LegacyArtifact {
	path := filepath.Join(dir, "nself.sh")
	_, err := os.Stat(path)
	if err != nil {
		return nil
	}
	return &LegacyArtifact{
		Path:        "nself.sh",
		Description: "v1 bootstrap script",
		Action:      "run: nself migrate",
	}
}
