package migration

import (
	"os"
	"path/filepath"
	"testing"
)

// writeFile creates a file at path with the given content, creating directories as needed.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("MkdirAll(%q): %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("WriteFile(%q): %v", path, err)
	}
}

// mkDir creates a directory at path.
func mkDir(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0755); err != nil {
		t.Fatalf("MkdirAll(%q): %v", path, err)
	}
}

func TestDetect_EmptyDir(t *testing.T) {
	dir := t.TempDir()
	artifacts := Detect(dir)
	if len(artifacts) != 0 {
		t.Errorf("expected no artifacts in empty dir, got %d: %v", len(artifacts), artifacts)
	}
}

func TestDetect_ComposeFile(t *testing.T) {
	tests := []struct {
		name       string
		content    string
		wantDetect bool
	}{
		{
			name:       "v1 generated compose",
			content:    "# Generated by nself\nversion: '3'\n",
			wantDetect: true,
		},
		{
			name:       "v2 generated compose",
			content:    "# Generated by nself\n# nself v2\nversion: '3'\n",
			wantDetect: false,
		},
		{
			name:       "unrelated compose",
			content:    "version: '3'\nservices:\n",
			wantDetect: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFile(t, filepath.Join(dir, "docker-compose.yml"), tc.content)
			artifacts := Detect(dir)
			got := containsPath(artifacts, "docker-compose.yml")
			if got != tc.wantDetect {
				t.Errorf("wantDetect=%v, got=%v (artifacts=%v)", tc.wantDetect, got, artifacts)
			}
		})
	}
}

func TestDetect_EnvFile(t *testing.T) {
	tests := []struct {
		name       string
		content    string
		wantDetect bool
	}{
		{
			name:       "v1 env with version 0.x",
			content:    "PROJECT_NAME=myapp\nNSELF_VERSION=0.9.9\n",
			wantDetect: true,
		},
		{
			name:       "v2 env with version 1.x",
			content:    "PROJECT_NAME=myapp\nNSELF_VERSION=1.0.0\n",
			wantDetect: false,
		},
		{
			name:       "env without nself version",
			content:    "PROJECT_NAME=myapp\n",
			wantDetect: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFile(t, filepath.Join(dir, ".env"), tc.content)
			artifacts := Detect(dir)
			got := containsPath(artifacts, ".env")
			if got != tc.wantDetect {
				t.Errorf("wantDetect=%v, got=%v (artifacts=%v)", tc.wantDetect, got, artifacts)
			}
		})
	}
}

func TestDetect_NginxDir(t *testing.T) {
	tests := []struct {
		name       string
		setup      func(dir string, t *testing.T)
		wantDetect bool
	}{
		{
			name: "v1 nginx dir without sites/",
			setup: func(dir string, t *testing.T) {
				mkDir(t, filepath.Join(dir, "nginx"))
				writeFile(t, filepath.Join(dir, "nginx", "nginx.conf"), "worker_processes 1;\n")
			},
			wantDetect: true,
		},
		{
			name: "v2 nginx dir with sites/",
			setup: func(dir string, t *testing.T) {
				mkDir(t, filepath.Join(dir, "nginx", "sites"))
			},
			wantDetect: false,
		},
		{
			name:       "no nginx dir",
			setup:      func(dir string, t *testing.T) {},
			wantDetect: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			tc.setup(dir, t)
			artifacts := Detect(dir)
			got := containsPath(artifacts, "nginx/")
			if got != tc.wantDetect {
				t.Errorf("wantDetect=%v, got=%v (artifacts=%v)", tc.wantDetect, got, artifacts)
			}
		})
	}
}

func TestDetect_NselfConfig(t *testing.T) {
	tests := []struct {
		name       string
		setup      func(dir string, t *testing.T)
		wantDetect bool
	}{
		{
			name: "v1 config is a file",
			setup: func(dir string, t *testing.T) {
				writeFile(t, filepath.Join(dir, ".nself", "config"), "version=0.9.9\n")
			},
			wantDetect: true,
		},
		{
			name: "v2 config is a directory",
			setup: func(dir string, t *testing.T) {
				mkDir(t, filepath.Join(dir, ".nself", "config"))
			},
			wantDetect: false,
		},
		{
			name:       "no .nself dir",
			setup:      func(dir string, t *testing.T) {},
			wantDetect: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			tc.setup(dir, t)
			artifacts := Detect(dir)
			got := containsPath(artifacts, ".nself/config")
			if got != tc.wantDetect {
				t.Errorf("wantDetect=%v, got=%v (artifacts=%v)", tc.wantDetect, got, artifacts)
			}
		})
	}
}

func TestDetect_BootstrapScript(t *testing.T) {
	tests := []struct {
		name       string
		setup      func(dir string, t *testing.T)
		wantDetect bool
	}{
		{
			name: "nself.sh exists",
			setup: func(dir string, t *testing.T) {
				writeFile(t, filepath.Join(dir, "nself.sh"), "#!/bin/bash\n# v1 bootstrap\n")
			},
			wantDetect: true,
		},
		{
			name:       "no nself.sh",
			setup:      func(dir string, t *testing.T) {},
			wantDetect: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			tc.setup(dir, t)
			artifacts := Detect(dir)
			got := containsPath(artifacts, "nself.sh")
			if got != tc.wantDetect {
				t.Errorf("wantDetect=%v, got=%v (artifacts=%v)", tc.wantDetect, got, artifacts)
			}
		})
	}
}

func TestDetect_MultipleArtifacts(t *testing.T) {
	dir := t.TempDir()

	// Plant all 5 artifacts
	writeFile(t, filepath.Join(dir, "docker-compose.yml"), "# Generated by nself\nversion: '3'\n")
	writeFile(t, filepath.Join(dir, ".env"), "NSELF_VERSION=0.9.9\n")
	mkDir(t, filepath.Join(dir, "nginx"))
	writeFile(t, filepath.Join(dir, ".nself", "config"), "version=0.9.9\n")
	writeFile(t, filepath.Join(dir, "nself.sh"), "#!/bin/bash\n")

	artifacts := Detect(dir)
	if len(artifacts) != 5 {
		t.Errorf("expected 5 artifacts, got %d: %v", len(artifacts), artifacts)
	}
}

// containsPath checks whether any artifact in the slice has the given path.
func containsPath(artifacts []LegacyArtifact, path string) bool {
	for _, a := range artifacts {
		if a.Path == path {
			return true
		}
	}
	return false
}
