import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:go_router/go_router.dart';

// airbnb-clone starter — generated by nself init --template airbnb-clone
// Replace HASURA_ENDPOINT with your actual endpoint from .env.dev
const _hasuraEndpoint = String.fromEnvironment(
  'HASURA_GRAPHQL_URL',
  defaultValue: 'http://localhost:8080/v1/graphql',
);

void main() async {
  await initHiveForFlutter();
  runApp(const AirbnbCloneApp());
}

class AirbnbCloneApp extends StatelessWidget {
  const AirbnbCloneApp({super.key});

  @override
  Widget build(BuildContext context) {
    final client = ValueNotifier(
      GraphQLClient(
        link: HttpLink(_hasuraEndpoint),
        cache: GraphQLCache(store: HiveStore()),
      ),
    );

    return GraphQLProvider(
      client: client,
      child: MaterialApp.router(
        title: 'Rental Marketplace',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFFF5A5F)),
          useMaterial3: true,
        ),
        routerConfig: _router,
      ),
    );
  }
}

final _router = GoRouter(
  routes: [
    GoRoute(path: '/', builder: (_, __) => const HomeScreen()),
    GoRoute(path: '/listing/:id', builder: (ctx, state) => ListingDetailScreen(id: state.pathParameters['id']!)),
    GoRoute(path: '/host', builder: (_, __) => const HostDashboardScreen()),
  ],
);

// ── Screens (stubs — replace with full implementations) ─────────────────────

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  static const _listingsQuery = r'''
    query GetListings {
      np_listings(where: {is_active: {_eq: true}}) {
        id title location price_per_night max_guests
      }
    }
  ''';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Rental Marketplace')),
      body: Query(
        options: QueryOptions(document: gql(_listingsQuery)),
        builder: (result, {fetchMore, refetch}) {
          if (result.isLoading) return const Center(child: CircularProgressIndicator());
          if (result.hasException) return Center(child: Text(result.exception.toString()));

          final listings = result.data?['np_listings'] as List? ?? [];
          return ListView.builder(
            itemCount: listings.length,
            itemBuilder: (ctx, i) {
              final l = listings[i] as Map<String, dynamic>;
              return ListTile(
                title: Text(l['title'] as String),
                subtitle: Text('${l['location']} — \$${l['price_per_night']}/night'),
                onTap: () => ctx.go('/listing/${l['id']}'),
              );
            },
          );
        },
      ),
    );
  }
}

class ListingDetailScreen extends StatelessWidget {
  final String id;
  const ListingDetailScreen({super.key, required this.id});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Listing')),
      body: Center(child: Text('Listing detail — id: $id')),
    );
  }
}

class HostDashboardScreen extends StatelessWidget {
  const HostDashboardScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Host Dashboard')),
      body: const Center(child: Text('Your listings and bookings appear here.')),
    );
  }
}
