source 'https://rubygems.org'

gem 'sinatra', '~> 3.1'
gem 'sinatra-contrib', '~> 3.1'
gem 'sinatra-cors', '~> 1.2'
gem 'puma', '~> 6.4'
gem 'pg', '~> 1.5'
gem 'redis', '~> 5.0'
gem 'json', '~> 2.7'
gem 'rack', '~> 2.2'

group :development do
  gem 'rerun', '~> 0.14'
end