import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:go_router/go_router.dart';

// notion-clone starter — generated by nself init --template notion-clone

const _hasuraEndpoint = String.fromEnvironment(
  'HASURA_GRAPHQL_URL',
  defaultValue: 'http://localhost:8080/v1/graphql',
);

void main() async {
  await initHiveForFlutter();
  runApp(const NotionCloneApp());
}

class NotionCloneApp extends StatelessWidget {
  const NotionCloneApp({super.key});

  @override
  Widget build(BuildContext context) {
    final client = ValueNotifier(
      GraphQLClient(
        link: HttpLink(_hasuraEndpoint),
        cache: GraphQLCache(store: HiveStore()),
      ),
    );
    return GraphQLProvider(
      client: client,
      child: MaterialApp.router(
        title: 'Workspace',
        theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.black), useMaterial3: true),
        routerConfig: _router,
      ),
    );
  }
}

final _router = GoRouter(
  routes: [
    GoRoute(path: '/', builder: (_, __) => const SidebarTreeScreen()),
    GoRoute(path: '/page/:id', builder: (ctx, state) => BlockEditorScreen(pageId: state.pathParameters['id']!)),
  ],
);

class SidebarTreeScreen extends StatelessWidget {
  const SidebarTreeScreen({super.key});

  static const _query = r'query { np_workspaces { id name pages(where: {parent_id: {_is_null: true}}) { id title icon } } }';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('My Workspace')),
      body: Query(
        options: QueryOptions(document: gql(_query)),
        builder: (result, {fetchMore, refetch}) {
          if (result.isLoading) return const Center(child: CircularProgressIndicator());
          final workspaces = result.data?['np_workspaces'] as List? ?? [];
          final pages = workspaces.isEmpty ? [] : (workspaces.first as Map)['pages'] as List? ?? [];
          return ListView.builder(
            itemCount: pages.length,
            itemBuilder: (ctx, i) {
              final p = pages[i] as Map<String, dynamic>;
              return ListTile(
                leading: Text(p['icon'] as String? ?? '📄'),
                title: Text(p['title'] as String),
                onTap: () => ctx.go('/page/${p['id']}'),
              );
            },
          );
        },
      ),
    );
  }
}

class BlockEditorScreen extends StatelessWidget {
  final String pageId;
  const BlockEditorScreen({super.key, required this.pageId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Page')),
      body: Center(child: Text('Block editor for page $pageId')),
    );
  }
}
