package commands

import (
	"fmt"
	"os"

	migratebash "github.com/nself-org/cli/internal/migrate"
	"github.com/nself-org/cli/internal/migration"
	"github.com/nself-org/cli/internal/ui"

	"github.com/spf13/cobra"
)

var migrateCmd = &cobra.Command{
	Use:   "migrate",
	Short: "Detect and migrate legacy artifacts to the current nSelf version",
	Long: `Scan the current project directory for legacy nSelf artifacts and report
what needs to be updated for compatibility.

Examples:
  nself migrate                # Scan current directory for legacy artifacts
  nself migrate detect         # Alias for the default scan
  nself migrate run            # Migrate v1 project to v2
  nself migrate rollback       # Restore from the most recent backup
  nself migrate --from-bash    # Guide migration from v0.9.9 Bash-era config`,
	RunE: runMigrate,
}

var migrateDetectCmd = &cobra.Command{
	Use:   "detect",
	Short: "Detect v1 artifacts in the current project",
	RunE:  runMigrate,
}

var migrateRunCmd = &cobra.Command{
	Use:   "run",
	Short: "Migrate v1 project to v2",
	Long: `Perform a full v1 → v2 migration.

Steps:
  1. Detect v1 artifacts (idempotent — exits cleanly if already v2)
  2. Stop running containers gracefully
  3. Backup current state to .nself/backup/{timestamp}/
  4. Move nginx configs to v2 layout (nginx/sites/)
  5. Regenerate docker-compose.yml, nginx, and SSL certificates
  6. Print migration summary

On any failure, run 'nself migrate rollback' to restore the previous state.`,
	RunE: runMigrateRun,
}

var migrateRollbackCmd = &cobra.Command{
	Use:   "rollback",
	Short: "Restore a v1 backup created by migrate run",
	Long: `Restore the project from the most recent migration backup.

Use --backup to select a specific backup by timestamp.
Use --list to see all available backups.`,
	RunE: runMigrateRollback,
}

// migrateFromBashCmd handles the --from-bash migration path. Operators running
// nSelf v0.9.9 (Bash era) have a different project layout (.nself/config.sh,
// docker-compose.yml without the GENERATED header, etc.). This subcommand
// detects that layout and guides the operator through the steps needed to
// migrate to the current Go-based CLI.
//
// Automated migration is P98 scope. This release provides detection + guided
// output + the most automatable steps (config file backup, .env.dev generation).
var migrateFromBashCmd = &cobra.Command{
	Use:   "from-bash",
	Short: "Migrate a v0.9.9 Bash-era project to the current nSelf CLI",
	Long: `Detect and guide migration from a v0.9.9 Bash-era nSelf project.

The Bash-era CLI (v0.9.9) used a different project layout:
  - .nself/config.sh (shell variable config, not .env cascade)
  - docker-compose.yml without the "GENERATED BY nself build" header
  - nself.sh bootstrap script at project root

This command:
  1. Scans the current directory for v0.9.9 artifacts
  2. Prints a step-by-step migration checklist with exact commands
  3. Optionally runs automatable steps (backup, .env.dev generation)

The command is idempotent: re-running on an already-migrated project prints
"Nothing to migrate" and exits cleanly.

Full migration guide: https://github.com/nself-org/cli/wiki/Upgrading-from-v0.9.9

Examples:
  nself migrate from-bash            # Detect and print migration guide
  nself migrate from-bash --auto     # Run automatable steps after confirmation`,
	RunE: runMigrateFromBash,
}

func init() {
	migrateRollbackCmd.Flags().String("backup", "", "Specific backup timestamp to restore (e.g. 20260328-143022)")
	migrateRollbackCmd.Flags().Bool("list", false, "List available backups with timestamps and sizes")

	migrateFromBashCmd.Flags().Bool("auto", false, "Run automatable migration steps after prompting for confirmation")
	migrateFromBashCmd.Flags().Bool("yes", false, "Skip confirmation prompts (non-interactive/CI mode). Implies --auto.")

	// Also support `nself migrate --from-bash` as a top-level flag for discoverability.
	migrateCmd.Flags().Bool("from-bash", false, "Migrate from a v0.9.9 Bash-era project (alias for: nself migrate from-bash)")

	migrateCmd.AddCommand(migrateDetectCmd)
	migrateCmd.AddCommand(migrateRunCmd)
	migrateCmd.AddCommand(migrateRollbackCmd)
	migrateCmd.AddCommand(migrateFromBashCmd)
	RootCmd.AddCommand(migrateCmd)
}

func runMigrate(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	artifacts := migration.Detect(cwd)

	if len(artifacts) == 0 {
		ui.Success("No v1 artifacts detected. This project is ready for nSelf v2.")
		return nil
	}

	fmt.Fprintf(cmd.ErrOrStderr(), "\n%s %s\n\n", ui.C(ui.Yellow, ui.IconWarning), ui.C(ui.Bold, "Legacy nSelf v1 artifacts detected:"))

	tbl := ui.NewTable("Path", "Description", "Action")
	for _, a := range artifacts {
		tbl.AddRow(a.Path, a.Description, a.Action)
	}
	tbl.Render()

	fmt.Println()
	ui.Warn(fmt.Sprintf("%d v1 artifact(s) found. Review the table above and migrate each item.", len(artifacts)))

	return nil
}

func runMigrateRun(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	return migration.Run(cmd.Context(), cwd)
}

func runMigrateRollback(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	listOnly, _ := cmd.Flags().GetBool("list")
	if listOnly {
		return printBackupList(cwd)
	}

	backupTimestamp, _ := cmd.Flags().GetString("backup")
	return migration.Rollback(cmd.Context(), cwd, backupTimestamp)
}

// printBackupList prints all available backups with timestamps and sizes.
func printBackupList(projectDir string) error {
	backups, err := migration.ListBackups(projectDir)
	if err != nil {
		return fmt.Errorf("listing backups: %w", err)
	}

	if len(backups) == 0 {
		ui.Warn("No backups found in .nself/backup/")
		return nil
	}

	fmt.Printf("\n%s %s\n\n", ui.C(ui.Blue, ui.IconInfo), ui.C(ui.Bold, "Available migration backups:"))

	tbl := ui.NewTable("Timestamp", "Size", "Path")
	for _, b := range backups {
		tbl.AddRow(b.Timestamp, formatBytes(b.Size), b.Dir)
	}
	tbl.Render()

	fmt.Println()
	ui.Info("Restore a backup: nself migrate rollback --backup <timestamp>")
	return nil
}

// runMigrateFromBash handles `nself migrate from-bash` (and the top-level
// `nself migrate --from-bash` alias). It detects v0.9.9 Bash-era artifacts,
// prints a guided migration checklist, and — when --auto is set — runs the
// automatable steps after confirmation.
func runMigrateFromBash(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	autoRun, _ := cmd.Flags().GetBool("auto")
	skipConfirm, _ := cmd.Flags().GetBool("yes")
	if skipConfirm {
		autoRun = true
	}

	// Detect v0.9.9 Bash-era artifacts.
	result := migratebash.DetectBashEra(cwd)

	if result.AlreadyMigrated {
		ui.Success("No v0.9.9 Bash-era artifacts detected. Nothing to migrate.")
		ui.Info("If you expected artifacts, verify you are in the project root directory.")
		return nil
	}

	// Print detected artifacts.
	fmt.Printf("\n%s %s\n\n",
		ui.C(ui.Yellow, ui.IconWarning),
		ui.C(ui.Bold, fmt.Sprintf("%d v0.9.9 Bash-era artifact(s) detected:", len(result.Artifacts))),
	)

	tbl := ui.NewTable("Path", "Description", "Auto-migrate?")
	for _, a := range result.Artifacts {
		auto := "manual"
		if a.AutoMigratable {
			auto = "yes"
		}
		tbl.AddRow(a.Path, a.Description, auto)
	}
	tbl.Render()

	// Print the full migration checklist.
	fmt.Printf("\n%s %s\n\n",
		ui.C(ui.Blue, ui.IconInfo),
		ui.C(ui.Bold, "Migration checklist (v0.9.9 → current):"),
	)

	steps := migratebash.MigrationChecklist(cwd)
	for _, step := range steps {
		p98tag := ""
		if step.P98Scope {
			p98tag = " [P98 scope — coming later]"
		}
		fmt.Printf("  %d. %s%s\n", step.Number, step.Title, p98tag)
		for _, c := range step.Commands {
			fmt.Printf("       %s\n", c)
		}
		if step.Notes != "" {
			fmt.Printf("     Note: %s\n", step.Notes)
		}
		fmt.Println()
	}

	fmt.Printf("  Full guide: https://github.com/nself-org/cli/wiki/Upgrading-from-v0.9.9\n\n")

	if !autoRun {
		ui.Info("To run automatable steps (backup + remove nself.sh), add --auto flag.")
		ui.Info("Review the checklist above and complete manual steps at your own pace.")
		return nil
	}

	// Confirm before running automated steps (unless --yes was set).
	if !skipConfirm {
		fmt.Print("Run automatable migration steps now? [y/N] ")
		var answer string
		if _, scanErr := fmt.Scanln(&answer); scanErr != nil || (answer != "y" && answer != "Y") {
			ui.Info("Aborted. No changes made.")
			return nil
		}
	}

	autoResult, err := migratebash.RunAuto(cwd, result)
	if err != nil {
		return fmt.Errorf("running automated migration steps: %w", err)
	}

	if autoResult.BackupDir != "" {
		ui.Success(fmt.Sprintf("Backup created: %s", autoResult.BackupDir))
	}
	for _, action := range autoResult.ActionsPerformed {
		ui.Success(fmt.Sprintf("Done: %s", action))
	}
	for _, skip := range autoResult.Skipped {
		ui.Info(fmt.Sprintf("Manual step required: %s", skip))
	}

	fmt.Println()
	ui.Info("Automated steps complete. Follow the remaining manual steps in the checklist above.")
	ui.Info("Next: review .envrc / docker-compose.yml, populate .env.dev, then run: nself build")

	return nil
}

// formatBytes returns a human-readable size string.
func formatBytes(b int64) string {
	const unit = 1024
	if b < unit {
		return fmt.Sprintf("%d B", b)
	}
	div, exp := int64(unit), 0
	for n := b / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(b)/float64(div), "KMGTPE"[exp])
}
