package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestWAFCmd_Structure verifies subcommands are registered.
func TestWAFCmd_Structure(t *testing.T) {
	subs := wafCmd.Commands()
	names := make(map[string]bool)
	for _, cmd := range subs {
		names[cmd.Name()] = true
	}
	for _, name := range []string{"enable", "mode", "report"} {
		if !names[name] {
			t.Errorf("waf: missing subcommand %q", name)
		}
	}
}

// TestWAFReportCmd_SinceFlag verifies the --since flag is registered with default "24h".
func TestWAFReportCmd_SinceFlag(t *testing.T) {
	f := wafReportCmd.Flags().Lookup("since")
	if f == nil {
		t.Fatal("waf report: --since flag not registered")
	}
	if f.DefValue != "24h" {
		t.Errorf("--since default = %q, want 24h", f.DefValue)
	}
}

// TestWAFModeCmd_ExactArgs verifies mode subcommand requires exactly one argument.
func TestWAFModeCmd_ExactArgs(t *testing.T) {
	if wafModeCmd.Args == nil {
		t.Fatal("waf mode: Args validator not set")
	}
}

// TestWAFCorazaConf_Content verifies that the Coraza config written by runWAFEnable
// contains required OWASP CRS include and SecRuleEngine directive.
func TestWAFCorazaConf_Content(t *testing.T) {
	tmp := t.TempDir()
	wafDir := filepath.Join(tmp, "nginx", "waf")
	crsDir := filepath.Join(wafDir, "crs")
	for _, d := range []string{wafDir, crsDir} {
		if err := os.MkdirAll(d, 0755); err != nil {
			t.Fatalf("mkdir %s: %v", d, err)
		}
	}

	// Write the same coraza.conf that runWAFEnable produces.
	corazaConf := `# Coraza WAF Configuration
# Generated by nself waf enable

SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecResponseBodyAccess Off

# OWASP CRS
Include /etc/nginx/waf/crs/*.conf

# Custom rules
Include /etc/nginx/waf/custom.conf

# Logging — waf_event label for Loki
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogType Serial
SecAuditLog /var/log/nginx/waf_audit.log
`
	corazaPath := filepath.Join(wafDir, "coraza.conf")
	if err := os.WriteFile(corazaPath, []byte(corazaConf), 0644); err != nil {
		t.Fatalf("write coraza.conf: %v", err)
	}

	data, err := os.ReadFile(corazaPath)
	if err != nil {
		t.Fatalf("read coraza.conf: %v", err)
	}
	content := string(data)

	// Coraza + OWASP CRS integration assertions.
	checks := []struct {
		needle string
		desc   string
	}{
		{"SecRuleEngine DetectionOnly", "default mode must be DetectionOnly"},
		{"Include /etc/nginx/waf/crs/*.conf", "OWASP CRS include must be present"},
		{"SecAuditLog", "audit log directive must be present"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("coraza.conf: %s — missing %q", c.desc, c.needle)
		}
	}
}

// TestWAFMode_ModeSwitch verifies the SecRuleEngine directive is toggled correctly.
func TestWAFMode_ModeSwitch(t *testing.T) {
	tmp := t.TempDir()
	wafDir := filepath.Join(tmp, "nginx", "waf")
	if err := os.MkdirAll(wafDir, 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	corazaPath := filepath.Join(wafDir, "coraza.conf")

	// Start in DetectionOnly.
	initial := "SecRuleEngine DetectionOnly\n"
	if err := os.WriteFile(corazaPath, []byte(initial), 0644); err != nil {
		t.Fatalf("write: %v", err)
	}

	// Simulate switching to blocking.
	data, _ := os.ReadFile(corazaPath)
	content := strings.Replace(string(data), "SecRuleEngine DetectionOnly", "SecRuleEngine On", 1)
	if err := os.WriteFile(corazaPath, []byte(content), 0644); err != nil {
		t.Fatalf("write: %v", err)
	}

	// Verify.
	after, _ := os.ReadFile(corazaPath)
	if !strings.Contains(string(after), "SecRuleEngine On") {
		t.Error("blocking mode: SecRuleEngine On not found after switch")
	}
	if strings.Contains(string(after), "SecRuleEngine DetectionOnly") {
		t.Error("blocking mode: SecRuleEngine DetectionOnly still present after switch")
	}
}

// TestWAFMode_InvalidMode verifies that an unsupported mode returns an error.
func TestWAFMode_InvalidMode(t *testing.T) {
	err := wafModeCmd.Args(wafModeCmd, []string{"invalid"})
	// ExactArgs(1) passes for one arg; actual validation is in RunE, so this
	// just confirms the command accepts exactly one arg at the cobra level.
	if err != nil {
		t.Errorf("unexpected cobra arg error: %v", err)
	}
}
