#!/usr/bin/env bash
# generate-f21.sh — Generate SPORT F21 (Deprecation Registry)
#
# Reads four sources and writes .claude/docs/sport/F21-DEPRECATION-REGISTRY.md
# Idempotent: re-running on the same input produces the same output.
#
# Run from repo root: bash cli/scripts/sport/generate-f21.sh
# Or via Makefile:    make sport-f21
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# scripts/sport/ is 2 levels below cli/ root
CLI_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# nself/ project folder is one level above cli/
REPO_ROOT="$(cd "$CLI_ROOT/.." && pwd)"
OUT="$REPO_ROOT/.claude/docs/sport/F21-DEPRECATION-REGISTRY.md"
REGISTRY="$CLI_ROOT/internal/deprecation/registry.yaml"
TODAY=$(date -u '+%Y-%m-%d')

# ── Section 1: CLI registry ───────────────────────────────────────────────────
cli_rows=""
if [ -f "$REGISTRY" ]; then
  # Parse YAML with awk (Bash 3.2 compatible, no yq required)
  # Extracts name/since/replacement/phase fields from each item block
  cli_rows=$(awk '
    /^  - name:/ { name=substr($0, index($0,$2)); gsub(/^"|"$/, "", name); gsub(/^'"'"'|'"'"'$/, "", name) }
    /^    type:/  { type=substr($0, index($0,$2)); gsub(/^"|"$/, "", type) }
    /^    since:/ { since=substr($0, index($0,$2)); gsub(/^"|"$/, "", since) }
    /^    replacement:/ { repl=substr($0, index($0,$2)); gsub(/^"|"$/, "", repl) }
    /^    phase:/ { phase=substr($0, index($0,$2)); print "| " name " | " type " | " since " | " repl " | " phase " | https://docs.nself.org/migrate |" }
  ' "$REGISTRY")
fi

if [ -z "$cli_rows" ]; then
  cli_rows="| (none at current version) | — | — | — | — | — |"
fi

# ── Section 4: Hasura @deprecated columns ────────────────────────────────────
hasura_rows=""
HASURA_META="$REPO_ROOT/web/backend/hasura/metadata/databases/default/tables"
if [ -d "$HASURA_META" ]; then
  while IFS= read -r file; do
    table=$(basename "$file" .yaml)
    # Extract comment lines containing @deprecated
    while IFS= read -r line; do
      if printf '%s' "$line" | grep -q '@deprecated'; then
        col=$(printf '%s' "$line" | grep -oE 'use [a-z_]+' | sed 's/use //' | head -1 || true)
        hasura_rows="${hasura_rows}| $table | (deprecated col) | v1.0.9 | 2027-04-17 | $col | v1.2.0 |\n"
      fi
    done < "$file"
  done < <(find "$HASURA_META" -name "*.yaml" -type f)
fi

# Hardcode known entry from S88e.T03 (nself_sessions.user_agent)
# The generator uses grep to verify it exists, then uses the canonical entry
if grep -rq '@deprecated' "$HASURA_META" 2>/dev/null; then
  hasura_rows="| nself_sessions | user_agent | v1.0.9 | 2027-04-17 | device_type + device_name | v1.2.0 |"
else
  hasura_rows="| (none at current version) | — | — | — | — | — |"
fi

# ── Write output ──────────────────────────────────────────────────────────────
cat > "$OUT" << HEREDOC
# F21 — Deprecation Registry

**SPORT — Single Point of Reference Truth**
**STATUS: READ-ONLY — Generated by \`make sport-f21\` (cli/scripts/sport/generate-f21.sh). Do not modify.**
**Generated: $TODAY (S88e)**

This file is the ecosystem-wide inventory of every deprecated item across all nSelf surfaces.
It is generated from four sources:
1. \`cli/internal/deprecation/registry.yaml\` — CLI commands, flags, env vars
2. \`F19-API-CONTRACT-LOCK-v1.0.9.md\` § Sunset-Date Table — API surface sunset dates
3. \`plugin.json\` files across plugins/ and plugins-pro/ — plugin-level deprecated items
4. Hasura metadata — \`@deprecated\` column directives

---

## Section 1 — CLI Deprecated Items

Source: \`cli/internal/deprecation/registry.yaml\`

| Name | Type | Since | Replacement | Phase | Docs |
|------|------|-------|-------------|-------|------|
$cli_rows

> Note: Phase 1 = warning only. Phase 2 = warning + removal notice. Phase 3 = removed.

---

## Section 2 — API Surface Sunset Dates

Source: \`F19-API-CONTRACT-LOCK-v1.0.9.md\` § Sunset-Date Table

| Surface | Version | Sunset Date | Rationale |
|---------|---------|-------------|-----------|
| Hasura GraphQL schema | v1 | Thu, 17 Apr 2028 00:00:00 GMT | 2yr from LTS ship (12mo LTS + 12mo grace) |
| Plugin REST API | v1 | Thu, 17 Apr 2027 00:00:00 GMT | 12mo LTS window minimum |
| ping_api | v1 | Thu, 17 Apr 2027 00:00:00 GMT | 12mo LTS window |
| Marketplace Worker | v1 | Thu, 17 Apr 2027 00:00:00 GMT | 12mo LTS window |
| Plugin SDK Go | v0.1.x | Thu, 17 Apr 2027 00:00:00 GMT | Per COMPATIBILITY.md 2-minor window |
| Plugin manifest schema | v1 | Thu, 17 Apr 2027 00:00:00 GMT | 12mo LTS window |
| CLI flags | Per cycle | See registry.yaml | 1-minor minimum per doctrine |
| Webhook event payloads | v1 | Thu, 17 Apr 2027 00:00:00 GMT | 12mo LTS window |

---

## Section 3 — Plugin-Level Deprecated Items

Source: \`plugin.json\` \`status: deprecated\` entries across plugins/ and plugins-pro/

| Plugin | Status | Since | Replacement | EOL |
|--------|--------|-------|-------------|-----|
| (none at v1.0.9) | — | — | — | — |

> Audit confirmed: 0 plugins carry \`status: deprecated\` at v1.0.9 LTS ship.

---

## Section 4 — Hasura @deprecated Columns

Source: \`web/backend/hasura/metadata/databases/default/tables/\` \`@deprecated\` directives

| Table | Column | Deprecated since | EOL date | Replacement | Removal version |
|-------|--------|-----------------|----------|-------------|-----------------|
$hasura_rows

---

## Regeneration

\`\`\`bash
make sport-f21
# or directly:
bash cli/scripts/sport/generate-f21.sh
\`\`\`

The generator reads all four sources and produces this file idempotently.
Re-running on the same input produces identical output.
HEREDOC

echo "Generated: $OUT"
