#!/usr/bin/env bash
# Purpose: regenerate the CLI command inventory from the cobra tree so SPORT F02,
#          the wiki command index, and the parity matrix stop being hand-typed.
#          Every prior count in those docs had drifted from the binary.
# Inputs:  none. Optional NSELF_SPORT_DIR to also refresh the SPORT F02 file
#          (it lives in the PPI, outside this repo, so it is only written when
#          that path is present on the machine running this).
# Outputs: .github/command-inventory.json  (machine-readable, committed)
#          .github/wiki/COMMANDS.md        (public command index, committed)
#          $NSELF_SPORT_DIR/F02-COMMAND-INVENTORY.md when the dir exists.
# Constraints: read-only against the source tree; must be idempotent so CI can
#              assert "regenerating produces no diff".
set -euo pipefail

cd "$(dirname "$0")/../.."

JSON_OUT=".github/command-inventory.json"
WIKI_OUT=".github/wiki/COMMANDS.md"

echo "Generating $JSON_OUT ..."
CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format json -depth 2 > "$JSON_OUT"

COUNT=$(CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format names | wc -l | tr -d ' ')

echo "Generating $WIKI_OUT ($COUNT top-level commands) ..."
{
  echo "# Commands"
  echo
  echo "<!-- GENERATED BY scripts/sport/generate-f02.sh — DO NOT HAND EDIT -->"
  echo
  echo "Every top-level \`nself\` command, generated from the cobra registration"
  echo "tree in \`cmd/commands/\`. Run \`make cmd-inventory\` to refresh."
  echo
  echo "**Total top-level commands: $COUNT**"
  echo
  CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format markdown -depth 2 \
    | sed '$d' | sed '$d'
  echo
  echo "---"
  echo
  echo "[[Home]] · [[CLI-Reference]] · [[Plugin-Overview]]"
} > "$WIKI_OUT"

if [ -n "${NSELF_SPORT_DIR:-}" ] && [ -d "${NSELF_SPORT_DIR}" ]; then
  SPORT_OUT="${NSELF_SPORT_DIR}/F02-COMMAND-INVENTORY.md"
  echo "Generating $SPORT_OUT ..."
  {
    echo "# F02 — CLI Command Inventory"
    echo
    echo "<!-- GENERATED BY cli/scripts/sport/generate-f02.sh — DO NOT HAND EDIT -->"
    echo
    echo "Last generated: $(date -u +%Y-%m-%d)"
    echo "Source: \`cli/cmd/commands\` cobra registration tree (not a hand count)."
    echo
    echo "**Counts: $COUNT top-level commands.** Subcommands listed but not counted separately."
    echo
    CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format markdown -depth 2 \
      | sed '$d' | sed '$d'
  } > "$SPORT_OUT"
else
  echo "NSELF_SPORT_DIR not set or missing — skipping SPORT F02 refresh."
fi

echo "Done. $COUNT top-level commands."
