#!/usr/bin/env bash
# generate-f17.sh — Generate SPORT F17-CLI-PLUGIN-COMPAT.md
# For each CLI version listed in MASTER-VERSIONS.md, enumerates:
#   - Compatible stable plugins
#   - Compatible beta plugins
#   - EOL plugins
# Runs at E2 Stage 0. S58-T05.
#
# Usage: bash cli/scripts/sport/generate-f17.sh
# Output: .claude/docs/sport/F17-CLI-PLUGIN-COMPAT.md
#
# Bash 3.2 compatible (macOS system shell).

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

FREE_REGISTRY="${REPO_ROOT}/plugins/registry.json"
PRO_REGISTRY="${REPO_ROOT}/plugins-pro/registry.json"
MASTER_VERSIONS="${REPO_ROOT}/.claude/docs/sport/F01-MASTER-VERSIONS.md"
OUT_FILE="${REPO_ROOT}/.claude/docs/sport/F17-CLI-PLUGIN-COMPAT.md"

if ! command -v jq >/dev/null 2>&1; then
  printf "error: jq is required to generate F17\n" >&2
  exit 1
fi

# Extract CLI versions from MASTER-VERSIONS.md — lines matching "| v<N>."
extract_cli_versions() {
  if [ ! -f "${MASTER_VERSIONS}" ]; then
    printf "1.0.9\n"
    return
  fi
  grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' "${MASTER_VERSIONS}" \
    | grep -i 'cli\|nself' \
    | sort -u \
    | sed 's/^v//' \
    | head -20 || printf "1.0.9\n"
}

# Given a registry file, emit plugin names with their status and minNselfVersion.
# Output: <name>\t<status>\t<minCLI>\t<maxCLI>
registry_plugins() {
  local path="$1"
  [ -f "${path}" ] || return 0
  jq -r '
    .plugins | to_entries[] |
    .key as $name |
    .value as $p |
    [
      $name,
      ($p.status // "stable"),
      ($p.minNselfVersion // $p.min_nself_version // "0.0.0"),
      ($p.maxNselfVersion // "99.99.99")
    ] | @tsv
  ' "${path}"
}

# semver_lte: returns 0 (true) if $1 <= $2, else 1.
# Compares major.minor.patch numerically.
semver_lte() {
  local a="$1" b="$2"
  local a1 a2 a3 b1 b2 b3
  a1=$(printf "%s" "${a}" | cut -d. -f1)
  a2=$(printf "%s" "${a}" | cut -d. -f2)
  a3=$(printf "%s" "${a}" | cut -d. -f3)
  b1=$(printf "%s" "${b}" | cut -d. -f1)
  b2=$(printf "%s" "${b}" | cut -d. -f2)
  b3=$(printf "%s" "${b}" | cut -d. -f3)
  if [ "${a1}" -lt "${b1}" ]; then return 0; fi
  if [ "${a1}" -gt "${b1}" ]; then return 1; fi
  if [ "${a2}" -lt "${b2}" ]; then return 0; fi
  if [ "${a2}" -gt "${b2}" ]; then return 1; fi
  if [ "${a3}" -le "${b3}" ]; then return 0; fi
  return 1
}

# Collect all plugin data once.
ALL_PLUGINS_TSV="$(
  registry_plugins "${FREE_REGISTRY}"
  registry_plugins "${PRO_REGISTRY}"
)"

# Write header.
cat > "${OUT_FILE}" << 'HEADER'
# F17 — CLI-PLUGIN-COMPAT

**SPORT — Single Point of Reference Truth**
Auto-generated by `cli/scripts/sport/generate-f17.sh`. Do not edit manually.
Regenerate: `bash cli/scripts/sport/generate-f17.sh`

S58-T05. Inverse of F18: for each CLI version, which plugins are compatible?

HEADER

# For each CLI version, write a section.
# Use current CLI version as the primary entry if extraction yields nothing useful.
CLI_VERSIONS="$(extract_cli_versions | sort -t. -k1,1n -k2,2n -k3,3n | uniq)"
if [ -z "${CLI_VERSIONS}" ]; then
  CLI_VERSIONS="1.0.9"
fi

printf "%s\n" "${CLI_VERSIONS}" | while read -r cli_ver; do
  printf "## v%s\n\n" "${cli_ver}" >> "${OUT_FILE}"
  printf "| Plugin | Status | Notes |\n" >> "${OUT_FILE}"
  printf "|--------|--------|-------|\n" >> "${OUT_FILE}"

  printf "%s\n" "${ALL_PLUGINS_TSV}" | while IFS="	" read -r name status min_cli max_cli; do
    # Check if cli_ver falls within [min_cli, max_cli].
    if semver_lte "${min_cli}" "${cli_ver}" && semver_lte "${cli_ver}" "${max_cli}"; then
      label=""
      case "${status}" in
        eol) label=" **[EOL]**" ;;
        deprecated) label=" *[deprecated]*" ;;
        beta) label=" *(beta)*" ;;
        experimental) label=" *(experimental)*" ;;
        planned) label=" *(planned)*" ;;
      esac
      printf "| %-30s | %-12s | %s |\n" "${name}" "${status}" "${label}" >> "${OUT_FILE}"
    fi
  done

  printf "\n" >> "${OUT_FILE}"
done

# Summary.
TOTAL_CLI=$(printf "%s\n" "${CLI_VERSIONS}" | wc -l | tr -d ' ')
cat >> "${OUT_FILE}" << FOOTER

## Summary

- **CLI versions covered:** ${TOTAL_CLI}
- **Generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
FOOTER

printf "F17 generated: %s\n" "${OUT_FILE}"
