#!/usr/bin/env bash
# generate-f18.sh — Generate SPORT F18-PLUGIN-COMPAT-MATRIX.md
# Reads registry.json from plugins/ and plugins-pro/ to produce a
# plugin → CLI compat matrix. Runs at E2 Stage 0 alongside other SPORT files.
# S58-T04 (named F18 to avoid collision with F16-PERF-SLOS per sprint note).
#
# Usage: bash cli/scripts/sport/generate-f18.sh
# Output: .claude/docs/sport/F18-PLUGIN-COMPAT-MATRIX.md
#
# Bash 3.2 compatible (macOS system shell).

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

FREE_REGISTRY="${REPO_ROOT}/plugins/registry.json"
PRO_REGISTRY="${REPO_ROOT}/plugins-pro/registry.json"
OUT_FILE="${REPO_ROOT}/.claude/docs/sport/F18-PLUGIN-COMPAT-MATRIX.md"

if ! command -v jq >/dev/null 2>&1; then
  printf "error: jq is required to generate F18\n" >&2
  exit 1
fi

# Collect entries from a registry JSON file.
# Args: registry_path source_label
emit_rows() {
  local path="$1"
  local source="$2"
  if [ ! -f "${path}" ]; then
    return
  fi
  # For each plugin key, extract fields with defaults for absent values.
  jq -r --arg src "${source}" '
    .plugins | to_entries[] |
    .key as $name |
    .value as $p |
    [
      $name,
      ($p.version // "?"),
      ($p.minNselfVersion // $p.min_nself_version // "-"),
      ($p.maxNselfVersion // "-"),
      "-",
      ($p.status // "stable"),
      (if $p.bundles then ($p.bundles | join(", ")) else "-" end),
      $src
    ] | @tsv
  ' "${path}"
}

# Header
cat > "${OUT_FILE}" << 'HEADER'
# F18 — PLUGIN-COMPAT-MATRIX

**SPORT — Single Point of Reference Truth**
Auto-generated by `cli/scripts/sport/generate-f18.sh`. Do not edit manually.
Regenerate: `bash cli/scripts/sport/generate-f18.sh`

S58-T04. Named F18 to avoid collision with F16-PERF-SLOS (S51-T01).

## Plugin → CLI Compatibility Matrix

| Plugin | Version | Min CLI | Max CLI | Min SDK | Status | Bundles | Source |
|--------|---------|---------|---------|---------|--------|---------|--------|
HEADER

# Collect all rows then append to file.
{
  emit_rows "${FREE_REGISTRY}" "free"
  if [ -f "${PRO_REGISTRY}" ]; then
    emit_rows "${PRO_REGISTRY}" "pro"
  fi
} | sort | while IFS="	" read -r name ver min_cli max_cli min_sdk status bundles src; do
  printf "| %-30s | %-9s | %-7s | %-7s | %-7s | %-10s | %-20s | %s |\n" \
    "${name}" "${ver}" "${min_cli}" "${max_cli}" "${min_sdk}" "${status}" "${bundles}" "${src}"
done >> "${OUT_FILE}"

# Footer with count.
ROW_COUNT=$(grep -c '^| ' "${OUT_FILE}" || true)
# Subtract the header row.
DATA_ROWS=$(( ROW_COUNT - 1 ))

cat >> "${OUT_FILE}" << FOOTER

## Summary

- **Total plugins:** ${DATA_ROWS}
- **Generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")

FOOTER

printf "F18 generated: %s (%d plugins)\n" "${OUT_FILE}" "${DATA_ROWS}"
