#!/usr/bin/env bash
# Purpose: publish the compose service catalog (required vs optional) as a
#          generated wiki page, and as SPORT F08's core-services section when
#          the PPI is present. CLI-R07: the split previously existed only as
#          control flow in generator.go, so every doc restating it drifted.
# Inputs:  optional NSELF_SPORT_DIR pointing at the PPI SPORT directory.
# Outputs: .github/wiki/Core-Services.md (committed)
#          $NSELF_SPORT_DIR/F08-CORE-SERVICES.md when the dir exists.
# Constraints: idempotent — CI asserts regenerating produces no diff.
set -euo pipefail

cd "$(dirname "$0")/../.."

OUT=".github/wiki/Core-Services.md"

echo "Generating $OUT ..."
{
  echo "# Core Services"
  echo
  echo "<!-- GENERATED BY scripts/sport/generate-core-services.sh — DO NOT HAND EDIT -->"
  echo
  echo "The services an nSelf stack is made of, generated from"
  echo "\`internal/compose/service_catalog.go\`. The same data backs"
  echo "\`nself service list --core\`, so the CLI and this page cannot disagree."
  echo
  CGO_ENABLED=0 go run -mod=vendor ./tools/servicecatalog -format markdown
  echo
  echo "## Checking your own stack"
  echo
  echo '```bash'
  echo "nself service list --core"
  echo '```'
  echo
  echo "---"
  echo
  echo "[[Home]] · [[COMMANDS]] · [[Config-Optional-Services]]"
} > "$OUT"

if [ -n "${NSELF_SPORT_DIR:-}" ] && [ -d "${NSELF_SPORT_DIR}" ]; then
  SPORT_OUT="${NSELF_SPORT_DIR}/F08-CORE-SERVICES.md"
  echo "Generating $SPORT_OUT ..."
  {
    echo "# F08 — Core Services (generated)"
    echo
    echo "<!-- GENERATED BY cli/scripts/sport/generate-core-services.sh — DO NOT HAND EDIT -->"
    echo
    echo "Last generated: $(date -u +%Y-%m-%d)"
    echo "Source: \`cli/internal/compose/service_catalog.go\`."
    echo
    CGO_ENABLED=0 go run -mod=vendor ./tools/servicecatalog -format markdown
  } > "$SPORT_OUT"
else
  echo "NSELF_SPORT_DIR not set or missing — skipping SPORT refresh."
fi

echo "Done."
