"""
my-plugin — nSelf plugin built with the Python SDK.
Generated by: nself plugin new my-plugin --lang python
"""

from nself_plugin import Plugin, PluginContext, HealthStatus

plugin = Plugin(name="my-plugin", version="1.0.0")


@plugin.install
async def install(ctx: PluginContext) -> None:
    ctx.logger.info("installing my-plugin")
    # Verify required env vars
    ctx.env.require([])
    # Register Nginx route
    from nself_plugin.context.nginx import RouteOptions
    ctx.nginx.add_route(RouteOptions(
        location="/my-plugin/",
        upstream=f"127.0.0.1:{ctx.port}",
    ))


@plugin.start
async def start(ctx: PluginContext) -> None:
    ctx.logger.info(f"starting my-plugin on port {ctx.port}")
    app = ctx.http.create_app()

    # Add your routes here
    @app.get("/my-plugin/hello")
    async def hello() -> dict[str, str]:
        return {"message": "Hello from my-plugin!"}

    await ctx.http.listen(ctx.port)


@plugin.health
async def health(ctx: PluginContext) -> HealthStatus:
    return await ctx.http.ping("/my-plugin/healthz")


@plugin.migrate
async def migrate(_ctx: PluginContext) -> None:
    # Run Hasura metadata or SQL migrations here
    pass


@plugin.uninstall
async def uninstall(ctx: PluginContext) -> None:
    ctx.logger.info("uninstalling my-plugin")
    ctx.nginx.remove_route("/my-plugin/")
