import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:go_router/go_router.dart';

// slack-clone starter — generated by nself init --template slack-clone

const _hasuraEndpoint = String.fromEnvironment(
  'HASURA_GRAPHQL_URL',
  defaultValue: 'http://localhost:8080/v1/graphql',
);

void main() async {
  await initHiveForFlutter();
  runApp(const SlackCloneApp());
}

class SlackCloneApp extends StatelessWidget {
  const SlackCloneApp({super.key});

  @override
  Widget build(BuildContext context) {
    final client = ValueNotifier(
      GraphQLClient(
        link: HttpLink(_hasuraEndpoint),
        cache: GraphQLCache(store: HiveStore()),
      ),
    );
    return GraphQLProvider(
      client: client,
      child: MaterialApp.router(
        title: 'Team Chat',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF4A154B)),
          useMaterial3: true,
        ),
        routerConfig: _router,
      ),
    );
  }
}

final _router = GoRouter(
  routes: [
    GoRoute(path: '/', builder: (_, __) => const WorkspacePickerScreen()),
    GoRoute(path: '/workspace/:id', builder: (ctx, state) => ChannelViewScreen(workspaceId: state.pathParameters['id']!)),
    GoRoute(path: '/channel/:id', builder: (ctx, state) => MessageViewScreen(channelId: state.pathParameters['id']!)),
  ],
);

class WorkspacePickerScreen extends StatelessWidget {
  const WorkspacePickerScreen({super.key});

  static const _query = r'query { np_workspaces { id name slug } }';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Workspaces')),
      body: Query(
        options: QueryOptions(document: gql(_query)),
        builder: (result, {fetchMore, refetch}) {
          if (result.isLoading) return const Center(child: CircularProgressIndicator());
          final workspaces = result.data?['np_workspaces'] as List? ?? [];
          return ListView.builder(
            itemCount: workspaces.length,
            itemBuilder: (ctx, i) {
              final w = workspaces[i] as Map<String, dynamic>;
              return ListTile(
                title: Text(w['name'] as String),
                subtitle: Text(w['slug'] as String),
                onTap: () => ctx.go('/workspace/${w['id']}'),
              );
            },
          );
        },
      ),
    );
  }
}

class ChannelViewScreen extends StatelessWidget {
  final String workspaceId;
  const ChannelViewScreen({super.key, required this.workspaceId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Channels')),
      body: Center(child: Text('Channels for workspace $workspaceId')),
    );
  }
}

class MessageViewScreen extends StatelessWidget {
  final String channelId;
  const MessageViewScreen({super.key, required this.channelId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('#channel')),
      body: Center(child: Text('Messages for channel $channelId')),
    );
  }
}
