services:
  nself:
    image: acamarata/nself:latest
    container_name: nself-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    working_dir: /workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - nself-network

networks:
  nself-network:
    driver: bridge