package compose

import (
	"fmt"

	"github.com/nself-org/cli/internal/config"

	"gopkg.in/yaml.v3"
)

// NginxConfDDir is the host-side directory for env-specific nginx conf.d files.
// Hand-managed, safe to edit directly.
const NginxConfDDir = "nginx/conf.d"

// NginxSitesDir is the host-side directory for generated nginx site configs.
// GENERATED by nself build — never hand-edit.
const NginxSitesDir = "nginx/sites"

// Generator builds a docker-compose.yml from project configuration.
type Generator struct {
	cfg *config.Config
}

// NewGenerator creates a compose Generator from the given config.
func NewGenerator(cfg *config.Config) *Generator {
	return &Generator{cfg: cfg}
}

// Generate produces the complete docker-compose.yml as YAML bytes.
// It marshals a DockerCompose struct via gopkg.in/yaml.v3.
func (g *Generator) Generate() ([]byte, error) {
	dc, err := g.buildDockerCompose()
	if err != nil {
		return nil, err
	}
	return yaml.Marshal(dc)
}

// buildDockerCompose constructs the full DockerCompose struct from config.
func (g *Generator) buildDockerCompose() (*DockerCompose, error) {
	dc := &DockerCompose{
		Name:     g.cfg.ProjectName,
		Networks: g.buildNetworks(),
		Volumes:  g.buildVolumes(),
		Services: make(map[string]ServiceConfig),
	}

	// Core services (always present) — postgres first, then dependents.
	dc.AddService("postgres", g.buildPostgresService())

	hasuraSvc, err := g.buildHasuraService()
	if err != nil {
		return nil, fmt.Errorf("building hasura service: %w", err)
	}
	dc.AddService("hasura", hasuraSvc)

	authSvc, err := g.buildAuthService()
	if err != nil {
		return nil, fmt.Errorf("building auth service: %w", err)
	}
	dc.AddService("auth", authSvc)

	// Optional services (conditional on config).
	// Init containers are inserted BEFORE the service that depends on them
	// so Docker Compose v5 sees definitions before depends_on references.
	if g.cfg.Redis.Enabled {
		dc.AddService("redis", g.buildRedisService())
	}
	if g.cfg.Minio.Enabled {
		dc.AddService("minio", g.buildMinioService())
	}
	if g.cfg.Mailpit.Enabled {
		dc.AddService("mailpit", g.buildMailpitService())
	}
	if g.cfg.Admin.Enabled {
		dc.AddService("nself-admin", g.buildAdminService())
	}
	if g.cfg.Functions.Enabled {
		dc.AddService("functions", g.buildFunctionsService())
	}
	// MLflow: handled by nself-mlflow free plugin (not in core)

	// Search (provider-based)
	if g.cfg.Search.Enabled {
		switch g.cfg.Search.Engine {
		case "meilisearch":
			dc.AddService("meilisearch-init", g.buildMeiliInitService())
			dc.AddService("meilisearch", g.buildMeiliService())
		case "typesense":
			dc.AddService("typesense", g.buildTypesenseService())
		}
	}

	// Monitoring: handled by nself-monitoring free plugin (not in core)
	// MLflow: handled by nself-mlflow free plugin (not in core)

	// Custom services
	for _, cs := range g.cfg.CustomServices {
		dc.AddService(cs.Name, g.buildCustomService(cs))
	}

	// Nginx (always last — depends on other services)
	dc.AddService("nginx", g.buildNginxService(dc))

	// Post-process: add logging, security, graceful shutdown to ALL services
	g.postProcess(dc)

	return dc, nil
}

// postProcess applies logging, security, and graceful shutdown to all services.
func (g *Generator) postProcess(dc *DockerCompose) {
	for name, svc := range dc.Services {
		// Logging: json-file driver with configurable max-size and max-file
		svc.Logging = &LoggingConfig{
			Driver: "json-file",
			Options: map[string]string{
				"max-size": g.cfg.DockerLogMaxSize,
				"max-file": g.cfg.DockerLogMaxFile,
			},
		}

		// Graceful shutdown
		svc.StopGrace = g.cfg.DockerStopGrace

		// Resource reservations: 256M minimum for all services.
		if svc.Deploy != nil && svc.Deploy.Resources != nil && svc.Deploy.Resources.Reservations == nil {
			svc.Deploy.Resources.Reservations = &ResourceLimits{
				Memory: "256m",
			}
		}

		// Security hardening — per-service profiles
		switch name {
		case "postgres":
			applySecurityToService(&svc, PostgresSecurity())
		case "minio":
			applySecurityToService(&svc, MinioSecurity())
		case "nginx":
			applySecurityToService(&svc, NginxSecurity())
		case "redis":
			applySecurityToService(&svc, RedisSecurity())
		default:
			applySecurityToService(&svc, DefaultSecurity())
		}

		dc.Services[name] = svc
	}
}

// Service builders are implemented in separate files:
// - core_services.go: postgres, hasura, auth, nginx
// - optional_services.go: redis, minio, mailpit, admin, functions, mlflow, search
// - monitoring_services.go: prometheus, grafana, loki, promtail, tempo, alertmanager, exporters, cadvisor
// - custom_services.go: user-defined custom services (CS_1..CS_10)
// - networks.go: docker-compose network definitions
// - volumes.go: docker-compose volume definitions
