package compose

import (
	"fmt"

	"github.com/nself-org/cli/internal/config"

	"gopkg.in/yaml.v3"
)

// NginxConfDDir is the host-side directory for env-specific nginx conf.d files.
// Hand-managed, safe to edit directly.
const NginxConfDDir = "nginx/conf.d"

// NginxSitesDir is the host-side directory for generated nginx site configs.
// GENERATED by nself build — never hand-edit.
const NginxSitesDir = "nginx/sites"

// Generator builds a docker-compose.yml from project configuration.
type Generator struct {
	cfg *config.Config
}

// NewGenerator creates a compose Generator from the given config.
func NewGenerator(cfg *config.Config) *Generator {
	return &Generator{cfg: cfg}
}

// Generate produces the complete docker-compose.yml as YAML bytes.
// It marshals a DockerCompose struct via gopkg.in/yaml.v3.
func (g *Generator) Generate() ([]byte, error) {
	dc, err := g.buildDockerCompose()
	if err != nil {
		return nil, err
	}
	return yaml.Marshal(dc)
}

// buildDockerCompose constructs the full DockerCompose struct from config.
func (g *Generator) buildDockerCompose() (*DockerCompose, error) {
	dc := &DockerCompose{
		Name:     g.cfg.ProjectName,
		Networks: g.buildNetworks(),
		Volumes:  g.buildVolumes(),
		Services: make(map[string]ServiceConfig),
	}

	// Core services (always present) — postgres first, then dependents.
	// When NSELF_EMBEDDED_PG=true, the Docker postgres container is omitted;
	// the embedded pglite/wasmtime runtime is booted by `nself start --embedded-pg`
	// and Hasura connects via a Unix-domain socket bridge.
	if !g.cfg.EmbeddedPG {
		dc.AddService("postgres", g.buildPostgresService())
	}

	hasuraSvc, err := g.buildHasuraService()
	if err != nil {
		return nil, fmt.Errorf("building hasura service: %w", err)
	}
	// When embedded PG is active, add the UDS socket volume mount so Hasura
	// can reach the pglite bridge at /var/run/postgres/pglite.sock.
	if g.cfg.EmbeddedPG {
		runtimeDirEnv := "${NSELF_RUNTIME_DIR:-.nself/embedded-pg}"
		hasuraSvc.Volumes = append(hasuraSvc.Volumes,
			runtimeDirEnv+"/pglite.sock.bridge:/var/run/postgres/pglite.sock",
		)
		// Remove the postgres health-check dependency — there is no postgres container.
		delete(hasuraSvc.DependsOn, "postgres")
	}
	dc.AddService("hasura", hasuraSvc)

	authSvc, err := g.buildAuthService()
	if err != nil {
		return nil, fmt.Errorf("building auth service: %w", err)
	}
	// When embedded PG is active, remove the postgres health-check dependency
	// from auth — there is no postgres container.
	if g.cfg.EmbeddedPG {
		delete(authSvc.DependsOn, "postgres")
	}
	dc.AddService("auth", authSvc)

	// Optional services (conditional on config).
	// Init containers are inserted BEFORE the service that depends on them
	// so Docker Compose v5 sees definitions before depends_on references.
	if g.cfg.Redis.Enabled {
		dc.AddService("redis", g.buildRedisService())
	}
	if g.cfg.Minio.Enabled {
		dc.AddService("minio", g.buildMinioService())
	}
	if g.cfg.Mailpit.Enabled {
		dc.AddService("mailpit", g.buildMailpitService())
	}
	if g.cfg.Admin.Enabled {
		dc.AddService("nself-admin", g.buildAdminService())
	}
	if g.cfg.Functions.Enabled {
		dc.AddService("functions", g.buildFunctionsService())
	}
	// MLflow: handled by nself-mlflow free plugin (not in core)

	// Search (provider-based)
	if g.cfg.Search.Enabled {
		switch g.cfg.Search.Engine {
		case "meilisearch":
			dc.AddService("meilisearch-init", g.buildMeiliInitService())
			dc.AddService("meilisearch", g.buildMeiliService())
		case "typesense":
			dc.AddService("typesense", g.buildTypesenseService())
		}
	}

	// Monitoring: handled by nself-monitoring free plugin (not in core)
	// MLflow: handled by nself-mlflow free plugin (not in core)

	// Custom services
	for _, cs := range g.cfg.CustomServices {
		dc.AddService(cs.Name, g.buildCustomService(cs))
	}

	// Nginx (always last — depends on other services)
	dc.AddService("nginx", g.buildNginxService(dc))

	// Post-process: add logging, security, graceful shutdown to ALL services
	g.postProcess(dc)

	return dc, nil
}

// defaultPidsLimit is the default pids_limit applied to every non-init container.
// Prevents fork-bomb attacks by capping processes+threads to 100. Services
// that legitimately spawn more threads (e.g. postgres under high concurrency)
// override PidsLimit directly in their builder function.
const defaultPidsLimit int64 = 100

// defaultMemLimit is the fallback memory cap applied to any generated service
// that does not set an explicit Deploy.Resources.Limits.Memory. Ensures no
// container can run unbounded in production.
const defaultMemLimit = "512m"

// defaultCPULimit is the fallback CPU cap applied to any generated service
// that does not set an explicit Deploy.Resources.Limits.CPUs.
const defaultCPULimit = "1.0"

// defaultMemReservation is the soft memory reservation applied to every
// service, guaranteeing a minimum allocation while the hard cap remains
// Deploy.Resources.Limits.Memory.
const defaultMemReservation = "256m"

// postProcess applies logging, security, and graceful shutdown to all services.
func (g *Generator) postProcess(dc *DockerCompose) {
	// Init containers are short-lived by design and should not be capped
	// by the service-wide resource policy (they exit before any limit matters).
	initContainers := map[string]bool{
		"meilisearch-init": true,
	}

	for name, svc := range dc.Services {
		// Logging: json-file driver with configurable max-size and max-file
		svc.Logging = &LoggingConfig{
			Driver: "json-file",
			Options: map[string]string{
				"max-size": g.cfg.DockerLogMaxSize,
				"max-file": g.cfg.DockerLogMaxFile,
			},
		}

		// Graceful shutdown
		svc.StopGrace = g.cfg.DockerStopGrace

		// Resource limits: every long-running service gets CPU+memory caps.
		// Services that already set Deploy.Resources.Limits (postgres, hasura,
		// auth, nginx, redis, custom_services) keep their per-service value;
		// others (minio, mailpit, admin, functions, meilisearch, typesense)
		// inherit the platform default so no container runs unbounded.
		if !initContainers[name] {
			if svc.Deploy == nil {
				svc.Deploy = &DeployConfig{}
			}
			if svc.Deploy.Resources == nil {
				svc.Deploy.Resources = &Resources{}
			}
			if svc.Deploy.Resources.Limits == nil {
				svc.Deploy.Resources.Limits = &ResourceLimits{}
			}
			if svc.Deploy.Resources.Limits.Memory == "" {
				svc.Deploy.Resources.Limits.Memory = defaultMemLimit
			}
			if svc.Deploy.Resources.Limits.CPUs == "" {
				svc.Deploy.Resources.Limits.CPUs = defaultCPULimit
			}
			if svc.Deploy.Resources.Reservations == nil {
				svc.Deploy.Resources.Reservations = &ResourceLimits{
					Memory: defaultMemReservation,
				}
			}
		}

		// Security hardening — per-service profiles
		switch name {
		case "postgres":
			applySecurityToService(&svc, PostgresSecurity())
		case "minio":
			applySecurityToService(&svc, MinioSecurity())
		case "nginx":
			applySecurityToService(&svc, NginxSecurity())
		case "redis":
			applySecurityToService(&svc, RedisSecurity())
		default:
			applySecurityToService(&svc, DefaultSecurity())
		}

		// Fork-bomb prevention: apply pids limit via deploy.resources.limits.pids
		// to every non-init long-running service. Uses modern Docker Compose syntax
		// (deploy.resources.limits.pids) instead of legacy pids_limit field.
		if !initContainers[name] {
			if svc.Deploy.Resources.Limits.Pids == 0 {
				svc.Deploy.Resources.Limits.Pids = defaultPidsLimit
			}
		}

		dc.Services[name] = svc
	}
}

// Service builders are implemented in separate files:
// - core_services.go: postgres, hasura, auth, nginx
// - optional_services.go: redis, minio, mailpit, admin, functions, mlflow, search
// - monitoring_services.go: prometheus, grafana, loki, promtail, tempo, alertmanager, exporters, cadvisor
// - custom_services.go: user-defined custom services (CS_1..CS_10)
// - networks.go: docker-compose network definitions
// - volumes.go: docker-compose volume definitions
