import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:go_router/go_router.dart';

// discord-clone starter — generated by nself init --template discord-clone

const _hasuraEndpoint = String.fromEnvironment(
  'HASURA_GRAPHQL_URL',
  defaultValue: 'http://localhost:8080/v1/graphql',
);

void main() async {
  await initHiveForFlutter();
  runApp(const DiscordCloneApp());
}

class DiscordCloneApp extends StatelessWidget {
  const DiscordCloneApp({super.key});

  @override
  Widget build(BuildContext context) {
    final client = ValueNotifier(
      GraphQLClient(
        link: HttpLink(_hasuraEndpoint),
        cache: GraphQLCache(store: HiveStore()),
      ),
    );
    return GraphQLProvider(
      client: client,
      child: MaterialApp.router(
        title: 'Community Chat',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF5865F2)),
          useMaterial3: true,
        ),
        routerConfig: _router,
      ),
    );
  }
}

final _router = GoRouter(
  routes: [
    GoRoute(path: '/', builder: (_, __) => const ServerListScreen()),
    GoRoute(path: '/server/:id', builder: (ctx, state) => ChannelListScreen(serverId: state.pathParameters['id']!)),
    GoRoute(path: '/channel/:id', builder: (ctx, state) => MessageViewScreen(channelId: state.pathParameters['id']!)),
  ],
);

class ServerListScreen extends StatelessWidget {
  const ServerListScreen({super.key});

  static const _query = r'query { np_servers { id name icon_url } }';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Servers')),
      body: Query(
        options: QueryOptions(document: gql(_query)),
        builder: (result, {fetchMore, refetch}) {
          if (result.isLoading) return const Center(child: CircularProgressIndicator());
          final servers = result.data?['np_servers'] as List? ?? [];
          return ListView.builder(
            itemCount: servers.length,
            itemBuilder: (ctx, i) {
              final s = servers[i] as Map<String, dynamic>;
              return ListTile(
                title: Text(s['name'] as String),
                onTap: () => ctx.go('/server/${s['id']}'),
              );
            },
          );
        },
      ),
    );
  }
}

class ChannelListScreen extends StatelessWidget {
  final String serverId;
  const ChannelListScreen({super.key, required this.serverId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Channels')),
      body: Center(child: Text('Channels for server $serverId')),
    );
  }
}

class MessageViewScreen extends StatelessWidget {
  final String channelId;
  const MessageViewScreen({super.key, required this.channelId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('#channel-$channelId')),
      body: const Center(child: Text('Messages appear here')),
    );
  }
}
