package setup

// setup_env_files.go — .env file generation for a new project.
//
// Purpose: write the standard and demo .env files (and set their permissions) for a freshly initialized project, used by Initialize in setup.go, split out for file size.
// The .env.example and --full multi-environment builders live in setup_env_files_full.go (further split for the same reason).
// Inputs: the resolved Options and secrets from setup_resolve.go.
// Outputs: .env files written to the project directory with 0600 permissions.
// Constraints: pure move from setup.go (CLI-R12 Batch E); no behaviour change. Per the CLI go.md rule, any code writing a .env* file chmods 0600 immediately after -- preserved as-is.

import (
	"fmt"
	"os"
	"path/filepath"
)

// WriteEnvFile writes env file content to path with restrictive 0600
// permissions (owner read/write only). Parent directories are created
// as needed.
func WriteEnvFile(path string, content []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory for env file: %w", err)
	}
	if err := os.WriteFile(path, content, 0600); err != nil {
		return fmt.Errorf("write env file %s: %w", path, err)
	}
	return nil
}

// EnsureEnvFilePermissions fixes the permissions of an existing env file to
// 0600 if they are more permissive. It is a no-op if the file does not exist.
func EnsureEnvFilePermissions(path string) error {
	info, err := os.Stat(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("stat env file %s: %w", path, err)
	}
	if info.Mode().Perm() != 0600 {
		if err := os.Chmod(path, 0600); err != nil {
			return fmt.Errorf("chmod env file %s: %w", path, err)
		}
	}
	return nil
}

// buildDomainLine builds the BASE_DOMAIN line with an optional preceding comment.
func buildDomainLine(baseDomain, domainComment string) string {
	if domainComment != "" {
		return domainComment + "\nBASE_DOMAIN=" + baseDomain
	}
	return "BASE_DOMAIN=" + baseDomain
}

// buildStandardEnv generates the default .env content. dbName is the
// SanitizeDBName-normalized POSTGRES_DB value, distinct from projectName
// (PROJECT_NAME) because the two have different valid-character sets — see
// config.SanitizeDBName.
func buildStandardEnv(projectName, dbName, baseDomain, env, pgPass, hasuraSecret, jwtKey, notifySecret, cronSecret, pluginInternalSecret, domainComment string, pgvectorEnabled bool) string {
	pgvectorVal := "true"
	if !pgvectorEnabled {
		pgvectorVal = "false"
	}
	return fmt.Sprintf(`# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# nSelf Project Configuration
# Generated by: nself init
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ── Core ──────────────────────────────────────────────────
PROJECT_NAME=%s
%s
ENV=%s

# ── PostgreSQL ────────────────────────────────────────────
POSTGRES_VERSION=16-alpine
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=%s
POSTGRES_USER=postgres
POSTGRES_PASSWORD=%s

# ── pgvector (RAG / vector search) ───────────────────────
PGVECTOR_ENABLED=%s
PGVECTOR_DIMENSIONS=1536
PGVECTOR_HNSW_M=16
PGVECTOR_HNSW_EF_CONSTRUCTION=64

# ── Hasura GraphQL ────────────────────────────────────────
HASURA_VERSION=v2.44.0
HASURA_GRAPHQL_ADMIN_SECRET=%s
HASURA_JWT_KEY=%s
HASURA_JWT_TYPE=HS256

# ── Auth ──────────────────────────────────────────────────
AUTH_ENABLED=true
AUTH_VERSION=0.36.0

# ── Nginx ─────────────────────────────────────────────────
NGINX_VERSION=alpine

# ── Optional Services (enable as needed) ──────────────────
REDIS_ENABLED=false
MINIO_ENABLED=false
MAILPIT_ENABLED=false
MONITORING_ENABLED=false
FUNCTIONS_ENABLED=false
ADMIN_ENABLED=false
SEARCH_ENABLED=false

# ── Plugin Secrets (auto-generated) ──────────────────────
NOTIFY_INTERNAL_SECRET=%s
CRON_INTERNAL_SECRET=%s
PLUGIN_INTERNAL_SECRET=%s
`, projectName, buildDomainLine(baseDomain, domainComment), env, dbName, pgPass, pgvectorVal, hasuraSecret, jwtKey, notifySecret, cronSecret, pluginInternalSecret)
}

// buildDemoEnv generates .env for --demo mode with all services enabled.
// dbName is the SanitizeDBName-normalized POSTGRES_DB value; see
// buildStandardEnv and config.SanitizeDBName for why it differs from
// projectName.
func buildDemoEnv(projectName, dbName, baseDomain, env, pgPass, hasuraSecret, jwtKey, minioPassword, notifySecret, cronSecret, pluginInternalSecret, domainComment string, pgvectorEnabled bool) string {
	pgvectorVal := "true"
	if !pgvectorEnabled {
		pgvectorVal = "false"
	}
	_ = pgvectorVal // used in format string below
	return fmt.Sprintf(`# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# nSelf Project Configuration (Demo Mode)
# Generated by: nself init --demo
# All services enabled with pre-configured defaults.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ── Core ──────────────────────────────────────────────────
PROJECT_NAME=%s
%s
ENV=%s

# ── PostgreSQL ────────────────────────────────────────────
POSTGRES_VERSION=16-alpine
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=%s
POSTGRES_USER=postgres
POSTGRES_PASSWORD=%s

# ── Hasura GraphQL ────────────────────────────────────────
HASURA_VERSION=v2.44.0
HASURA_GRAPHQL_ADMIN_SECRET=%s
HASURA_JWT_KEY=%s
HASURA_JWT_TYPE=HS256
HASURA_GRAPHQL_ENABLE_CONSOLE=true
HASURA_GRAPHQL_DEV_MODE=true

# ── Auth ──────────────────────────────────────────────────
AUTH_ENABLED=true
AUTH_VERSION=0.36.0

# ── Nginx ─────────────────────────────────────────────────
NGINX_VERSION=alpine

# ── Redis ─────────────────────────────────────────────────
REDIS_ENABLED=true
REDIS_VERSION=7-alpine

# ── MinIO / Storage ───────────────────────────────────────
MINIO_ENABLED=true
MINIO_ROOT_USER=nself
MINIO_ROOT_PASSWORD=%s

# ── Mailpit (Dev Email) ──────────────────────────────────
MAILPIT_ENABLED=true

# ── Monitoring Stack ──────────────────────────────────────
# Install monitoring plugin: nself plugin install monitoring
MONITORING_ENABLED=false

# ── Functions Runtime ─────────────────────────────────────
FUNCTIONS_ENABLED=true

# ── Admin Dashboard ───────────────────────────────────────
ADMIN_ENABLED=true

# ── Search (MeiliSearch) ──────────────────────────────────
SEARCH_ENABLED=true
SEARCH_ENGINE=meilisearch

# ── Example Custom Services ──────────────────────────────
CS_1_NAME=ping-api
CS_1_FRAMEWORK=node
CS_1_PORT=8001
CS_1_ROUTE=ping

CS_2_NAME=worker
CS_2_FRAMEWORK=node
CS_2_PORT=8002
CS_2_ROUTE=worker

# ── Example Frontend Apps ─────────────────────────────────
FRONTEND_APP_1_NAME=web
FRONTEND_APP_1_PORT=3000
FRONTEND_APP_1_ROUTE=app

FRONTEND_APP_2_NAME=admin-ui
FRONTEND_APP_2_PORT=3001
FRONTEND_APP_2_ROUTE=dashboard

# ── Plugin Secrets (auto-generated) ──────────────────────
NOTIFY_INTERNAL_SECRET=%s
CRON_INTERNAL_SECRET=%s
PLUGIN_INTERNAL_SECRET=%s
`, projectName, buildDomainLine(baseDomain, domainComment), env, dbName, pgPass, hasuraSecret, jwtKey, minioPassword, notifySecret, cronSecret, pluginInternalSecret)
}

// buildExampleEnv and writeFullEnvFiles moved to setup_env_files_full.go
// (CLI go.md 300-line file cap).
