package setup

// setup_env_files_full.go — .env.example and --full multi-environment file
// generation for a new project.
//
// Purpose: split out of setup_env_files.go (CLI go.md 300-line file cap) —
// buildExampleEnv and writeFullEnvFiles have no behavioural relationship to
// the standard/demo .env builders beyond sharing the package, so they move
// cleanly.
// Inputs: the resolved project name and base domain from setup_resolve.go.
// Outputs: .env.example (always) and .env.dev/.env.staging/.env.prod/.env.secrets
// (only under --full) written to the project directory.
// Constraints: pure move, no behaviour change. Per the CLI go.md rule, any
// code writing a .env* file chmods 0600 immediately after — preserved as-is
// (.env.example is the one exception, written 0644 by the caller in setup.go
// since it carries no secrets).

import (
	"fmt"
	"path/filepath"
)

// buildExampleEnv generates the .env.example (no real secrets).
func buildExampleEnv(projectName, baseDomain, env string, demo bool) string {
	mode := ""
	if demo {
		mode = " (Demo Mode)"
	}
	return fmt.Sprintf(`# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# nSelf Project Configuration%s
# Copy to .env and fill in your secrets.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROJECT_NAME=%s
BASE_DOMAIN=%s
ENV=%s

POSTGRES_PASSWORD=CHANGE_ME
HASURA_GRAPHQL_ADMIN_SECRET=CHANGE_ME
HASURA_JWT_KEY=CHANGE_ME
`, mode, projectName, baseDomain, env)
}

// writeFullEnvFiles creates .env.dev, .env.staging, .env.prod, .env.secrets.
func writeFullEnvFiles(workDir, projectName, baseDomain string) ([]string, error) {
	var created []string

	// .env.dev
	devContent := `# Development environment overrides
ENV=dev
BASE_DOMAIN=local.nself.org
HASURA_GRAPHQL_ENABLE_CONSOLE=true
HASURA_GRAPHQL_DEV_MODE=true
`
	if err := writeFile(filepath.Join(workDir, ".env.dev"), devContent, 0600); err != nil {
		return nil, err
	}
	created = append(created, ".env.dev")

	// .env.staging
	stagingContent := fmt.Sprintf(`# Staging environment overrides
ENV=staging
BASE_DOMAIN=staging.%s
HASURA_GRAPHQL_ENABLE_CONSOLE=false
HASURA_GRAPHQL_DEV_MODE=false
`, baseDomain)
	if err := writeFile(filepath.Join(workDir, ".env.staging"), stagingContent, 0600); err != nil {
		return nil, err
	}
	created = append(created, ".env.staging")

	// .env.prod
	prodContent := fmt.Sprintf(`# Production environment overrides
ENV=prod
BASE_DOMAIN=%s
HASURA_GRAPHQL_ENABLE_CONSOLE=false
HASURA_GRAPHQL_DEV_MODE=false
`, baseDomain)
	if err := writeFile(filepath.Join(workDir, ".env.prod"), prodContent, 0600); err != nil {
		return nil, err
	}
	created = append(created, ".env.prod")

	// .env.secrets (600 perms, gitignored)
	pgPass, err := GenerateSecret(32)
	if err != nil {
		return nil, fmt.Errorf("generating postgres password for secrets file: %w", err)
	}
	hasuraSecret, err := GenerateSecret(44)
	if err != nil {
		return nil, fmt.Errorf("generating hasura secret for secrets file: %w", err)
	}
	jwtKey, err := GenerateSecret(44)
	if err != nil {
		return nil, fmt.Errorf("generating JWT key for secrets file: %w", err)
	}
	secretsContent := fmt.Sprintf(`# Secrets — DO NOT COMMIT
# Auto-generated by nself init --full
POSTGRES_PASSWORD=%s
HASURA_GRAPHQL_ADMIN_SECRET=%s
HASURA_JWT_KEY=%s
`, pgPass, hasuraSecret, jwtKey)
	if err := writeFile(filepath.Join(workDir, ".env.secrets"), secretsContent, 0600); err != nil {
		return nil, err
	}
	created = append(created, ".env.secrets")

	return created, nil
}
