// Package migrate provides migration helpers for legacy nSelf project layouts.
// The v1→v2 migration lives in internal/migration. This package handles the
// older v0.9.9 Bash-era migration path (--from-bash).
package migrate

import (
	"os"
	"path/filepath"
	"strings"
)

// BashEraArtifact describes a v0.9.9 Bash-era artifact found in a project
// directory. Each artifact carries the action the operator must take.
type BashEraArtifact struct {
	// Path is the path relative to the project directory where the artifact
	// was found.
	Path string
	// Description is a human-readable description of what the artifact is.
	Description string
	// Action is the exact step the operator must take to resolve it.
	Action string
	// AutoMigratable is true when RunAuto can handle this artifact without
	// operator input beyond the initial confirmation.
	AutoMigratable bool
}

// BashDetectResult holds the outcome of DetectBashEra.
type BashDetectResult struct {
	// Artifacts is the list of v0.9.9 artifacts found. Empty means clean.
	Artifacts []BashEraArtifact
	// AlreadyMigrated is true when the project directory shows no Bash-era
	// artifacts at all — the project is already on the Go-based CLI.
	AlreadyMigrated bool
}

// DetectBashEra scans projectDir for v0.9.9 Bash-era artifacts.
// It does not modify anything — detection is always read-only.
//
// The function returns BashDetectResult. When AlreadyMigrated is true and
// Artifacts is empty, the project is clean and nothing needs to be done.
//
// False positives are avoided by requiring the artifact to be unambiguously
// Bash-era (e.g. .nself/config.sh must contain NSELF_VERSION= with a 0.9.x
// value, not just any shell file named config.sh).
func DetectBashEra(projectDir string) BashDetectResult {
	var artifacts []BashEraArtifact

	// 1. .nself/config.sh — canonical Bash-era config file.
	if a := detectConfigSh(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	// 2. docker-compose.yml without the "GENERATED BY nself build" header.
	if a := detectBashCompose(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	// 3. nself.sh bootstrap script at project root.
	if a := detectNselfSh(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	// 4. .env missing but .envrc present (Bash-era used direnv / .envrc).
	if a := detectEnvrc(projectDir); a != nil {
		artifacts = append(artifacts, *a)
	}

	return BashDetectResult{
		Artifacts:       artifacts,
		AlreadyMigrated: len(artifacts) == 0,
	}
}

// detectConfigSh checks for a v0.9.9 .nself/config.sh file that contains
// NSELF_VERSION= with a 0.9.x value. A config.sh without the version marker
// is not flagged to avoid false positives on projects that happen to have a
// similarly named file.
func detectConfigSh(dir string) *BashEraArtifact {
	p := filepath.Join(dir, ".nself", "config.sh")
	data, err := os.ReadFile(p)
	if err != nil {
		return nil
	}
	content := string(data)
	// Only flag if it looks like a genuine v0.9.x config.
	if strings.Contains(content, "NSELF_VERSION=0.9") || strings.Contains(content, "# nself config v0.9") {
		return &BashEraArtifact{
			Path:           ".nself/config.sh",
			Description:    "v0.9.9 shell variable config (replaced by .env cascade in v1+)",
			Action:         "Run: nself migrate from-bash --auto  OR follow the manual guide",
			AutoMigratable: true,
		}
	}
	return nil
}

// detectBashCompose checks for a docker-compose.yml that was hand-written in
// the Bash era (lacks the "GENERATED BY nself build" header that the Go CLI
// always prepends). A compose file is only flagged when it also lacks the v2
// header, to avoid false positives on brand-new projects that haven't run
// nself build yet.
func detectBashCompose(dir string) *BashEraArtifact {
	p := filepath.Join(dir, "docker-compose.yml")
	data, err := os.ReadFile(p)
	if err != nil {
		return nil
	}
	content := string(data)
	// The Go CLI always writes the GENERATED header. The v2 migration header is
	// also acceptable. A compose file without either is Bash-era.
	hasGoHeader := strings.Contains(content, "GENERATED BY nself build")
	hasV2Header := strings.Contains(content, "nself v2")
	if !hasGoHeader && !hasV2Header {
		return &BashEraArtifact{
			Path:           "docker-compose.yml",
			Description:    "v0.9.9 hand-written compose file (must be regenerated by nself build)",
			Action:         "Back up your compose file, then run: nself build",
			AutoMigratable: false, // operator must review before overwrite
		}
	}
	return nil
}

// detectNselfSh checks for a nself.sh bootstrap script at project root.
// This script was the main entry point in v0.9.9 and is not used in v1+.
func detectNselfSh(dir string) *BashEraArtifact {
	p := filepath.Join(dir, "nself.sh")
	_, err := os.Stat(p)
	if err != nil {
		return nil
	}
	return &BashEraArtifact{
		Path:           "nself.sh",
		Description:    "v0.9.9 bootstrap script (replaced by the nself binary)",
		Action:         "Remove: rm nself.sh  (keep a copy if you need to reference it)",
		AutoMigratable: true,
	}
}

// detectEnvrc checks for a .envrc file at project root. In v0.9.9, direnv
// was recommended for loading environment variables. The Go CLI uses the
// .env cascade and does not require .envrc.
func detectEnvrc(dir string) *BashEraArtifact {
	p := filepath.Join(dir, ".envrc")
	_, err := os.Stat(p)
	if err != nil {
		return nil
	}
	return &BashEraArtifact{
		Path:           ".envrc",
		Description:    "v0.9.9 direnv file (env vars now managed via .env cascade)",
		Action:         "Review .envrc, copy vars to .env.dev, then remove .envrc",
		AutoMigratable: false, // operator must review content before removal
	}
}
