package migrate

import (
	"os"
	"path/filepath"
	"testing"
)

// writeFile is a test helper that creates a file with the given content.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("MkdirAll %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("WriteFile %s: %v", path, err)
	}
}

// ── DetectBashEra ─────────────────────────────────────────────────────────────

// TestDetectBashEra_CleanProject verifies that a clean v1+ project (no
// Bash-era artifacts) is reported as already migrated.
func TestDetectBashEra_CleanProject(t *testing.T) {
	dir := t.TempDir()
	result := DetectBashEra(dir)

	if !result.AlreadyMigrated {
		t.Errorf("expected AlreadyMigrated=true for empty dir, got false; artifacts: %v", result.Artifacts)
	}
	if len(result.Artifacts) != 0 {
		t.Errorf("expected 0 artifacts for clean dir, got %d: %v", len(result.Artifacts), result.Artifacts)
	}
}

// TestDetectBashEra_ConfigSh verifies detection of a v0.9.9 .nself/config.sh.
func TestDetectBashEra_ConfigSh(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".nself", "config.sh"),
		"# nself config v0.9\nNSELF_VERSION=0.9.9\nPROJECT_NAME=myapp\n")

	result := DetectBashEra(dir)
	if result.AlreadyMigrated {
		t.Error("expected AlreadyMigrated=false when config.sh present")
	}
	found := false
	for _, a := range result.Artifacts {
		if a.Path == ".nself/config.sh" {
			found = true
			if !a.AutoMigratable {
				t.Errorf("config.sh artifact should be AutoMigratable=true")
			}
		}
	}
	if !found {
		t.Errorf("expected .nself/config.sh artifact, got: %v", result.Artifacts)
	}
}

// TestDetectBashEra_NselfSh verifies detection of the v0.9.9 nself.sh script.
func TestDetectBashEra_NselfSh(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "nself.sh"), "#!/usr/bin/env bash\n# v0.9 bootstrap\n")

	result := DetectBashEra(dir)
	if result.AlreadyMigrated {
		t.Error("expected AlreadyMigrated=false when nself.sh present")
	}
	found := false
	for _, a := range result.Artifacts {
		if a.Path == "nself.sh" {
			found = true
			if !a.AutoMigratable {
				t.Errorf("nself.sh artifact should be AutoMigratable=true")
			}
		}
	}
	if !found {
		t.Errorf("expected nself.sh artifact, got: %v", result.Artifacts)
	}
}

// TestDetectBashEra_BashComposeFile verifies detection of a hand-written
// (Bash-era) docker-compose.yml that lacks the GENERATED header.
func TestDetectBashEra_BashComposeFile(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "docker-compose.yml"),
		"version: '3.8'\nservices:\n  postgres:\n    image: postgres:15\n")

	result := DetectBashEra(dir)
	if result.AlreadyMigrated {
		t.Error("expected AlreadyMigrated=false for hand-written docker-compose.yml")
	}
	found := false
	for _, a := range result.Artifacts {
		if a.Path == "docker-compose.yml" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected docker-compose.yml artifact, got: %v", result.Artifacts)
	}
}

// TestDetectBashEra_GoGeneratedComposeNotFlagged verifies that a compose file
// written by the Go CLI (contains the GENERATED header) is NOT flagged.
func TestDetectBashEra_GoGeneratedComposeNotFlagged(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "docker-compose.yml"),
		"# GENERATED BY nself build - DO NOT HAND EDIT\nservices:\n  postgres:\n    image: postgres:15\n")

	result := DetectBashEra(dir)
	for _, a := range result.Artifacts {
		if a.Path == "docker-compose.yml" {
			t.Errorf("Go-generated docker-compose.yml should NOT be flagged as Bash-era artifact")
		}
	}
}

// TestDetectBashEra_ConfigShWithoutVersionNotFlagged verifies that a
// .nself/config.sh that lacks the NSELF_VERSION=0.9 marker does not trigger a
// false positive (avoids flagging unrelated config.sh files).
func TestDetectBashEra_ConfigShWithoutVersionNotFlagged(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".nself", "config.sh"),
		"# Some unrelated shell script\necho hello\n")

	result := DetectBashEra(dir)
	for _, a := range result.Artifacts {
		if a.Path == ".nself/config.sh" {
			t.Errorf("config.sh without v0.9 marker should NOT be flagged; got artifact: %+v", a)
		}
	}
}

// TestDetectBashEra_Envrc verifies detection of a .envrc file.
func TestDetectBashEra_Envrc(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".envrc"), "export PROJECT_NAME=myapp\n")

	result := DetectBashEra(dir)
	found := false
	for _, a := range result.Artifacts {
		if a.Path == ".envrc" {
			found = true
			// .envrc is not auto-migratable — operator must review content.
			if a.AutoMigratable {
				t.Errorf(".envrc artifact should NOT be AutoMigratable (operator must review)")
			}
		}
	}
	if !found {
		t.Errorf("expected .envrc artifact, got: %v", result.Artifacts)
	}
}

// ── MigrationChecklist ────────────────────────────────────────────────────────

// TestMigrationChecklist_NonEmpty verifies the checklist has steps.
func TestMigrationChecklist_NonEmpty(t *testing.T) {
	steps := MigrationChecklist("/tmp/fake-project")
	if len(steps) == 0 {
		t.Error("MigrationChecklist returned empty step list")
	}
}

// TestMigrationChecklist_NumbersAreSequential verifies steps are numbered 1..N.
func TestMigrationChecklist_NumbersAreSequential(t *testing.T) {
	steps := MigrationChecklist("/tmp/fake-project")
	for i, step := range steps {
		want := i + 1
		if step.Number != want {
			t.Errorf("step[%d].Number = %d, want %d", i, step.Number, want)
		}
	}
}

// TestMigrationChecklist_EachStepHasTitle verifies every step has a non-empty title.
func TestMigrationChecklist_EachStepHasTitle(t *testing.T) {
	steps := MigrationChecklist("/tmp/fake-project")
	for _, step := range steps {
		if step.Title == "" {
			t.Errorf("step %d has empty Title", step.Number)
		}
	}
}

// ── RunAuto ───────────────────────────────────────────────────────────────────

// TestRunAuto_AlreadyMigrated verifies RunAuto is a no-op on a clean project.
func TestRunAuto_AlreadyMigrated(t *testing.T) {
	dir := t.TempDir()
	result := BashDetectResult{AlreadyMigrated: true}

	out, err := RunAuto(dir, result)
	if err != nil {
		t.Fatalf("RunAuto: %v", err)
	}
	if len(out.ActionsPerformed) != 0 {
		t.Errorf("expected no actions on already-migrated project, got: %v", out.ActionsPerformed)
	}
}

// TestRunAuto_RemovesNselfSh verifies RunAuto removes nself.sh and backs it up.
func TestRunAuto_RemovesNselfSh(t *testing.T) {
	dir := t.TempDir()
	nselfSh := filepath.Join(dir, "nself.sh")
	writeFile(t, nselfSh, "#!/usr/bin/env bash\n# v0.9 bootstrap\n")

	result := BashDetectResult{
		AlreadyMigrated: false,
		Artifacts: []BashEraArtifact{
			{Path: "nself.sh", Description: "v0.9 bootstrap", Action: "remove", AutoMigratable: true},
		},
	}

	out, err := RunAuto(dir, result)
	if err != nil {
		t.Fatalf("RunAuto: %v", err)
	}

	// nself.sh must no longer exist.
	if _, statErr := os.Stat(nselfSh); statErr == nil {
		t.Error("nself.sh still exists after RunAuto — expected removal")
	}

	// Backup directory must exist.
	if out.BackupDir == "" {
		t.Error("expected non-empty BackupDir in result")
	}
	if _, statErr := os.Stat(out.BackupDir); statErr != nil {
		t.Errorf("backup directory %s does not exist: %v", out.BackupDir, statErr)
	}

	// Backup must contain the file.
	backedUp := filepath.Join(out.BackupDir, "nself.sh")
	if _, statErr := os.Stat(backedUp); statErr != nil {
		t.Errorf("nself.sh not found in backup dir %s: %v", out.BackupDir, statErr)
	}
}

// TestRunAuto_Idempotent verifies RunAuto can be called twice without error.
// Second call finds no artifacts (nself.sh already removed) and no-ops cleanly.
func TestRunAuto_Idempotent(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "nself.sh"), "#!/usr/bin/env bash\n")

	artifacts := []BashEraArtifact{
		{Path: "nself.sh", AutoMigratable: true},
	}

	// First call removes nself.sh.
	_, err := RunAuto(dir, BashDetectResult{Artifacts: artifacts})
	if err != nil {
		t.Fatalf("first RunAuto: %v", err)
	}

	// Second call on already-migrated state must not error.
	result2 := DetectBashEra(dir)
	_, err = RunAuto(dir, result2)
	if err != nil {
		t.Fatalf("second RunAuto (idempotency check): %v", err)
	}
}
