import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:go_router/go_router.dart';

// substack-clone starter — generated by nself init --template substack-clone

const _hasuraEndpoint = String.fromEnvironment(
  'HASURA_GRAPHQL_URL',
  defaultValue: 'http://localhost:8080/v1/graphql',
);

void main() async {
  await initHiveForFlutter();
  runApp(const SubstackCloneApp());
}

class SubstackCloneApp extends StatelessWidget {
  const SubstackCloneApp({super.key});

  @override
  Widget build(BuildContext context) {
    final client = ValueNotifier(
      GraphQLClient(
        link: HttpLink(_hasuraEndpoint),
        cache: GraphQLCache(store: HiveStore()),
      ),
    );
    return GraphQLProvider(
      client: client,
      child: MaterialApp.router(
        title: 'Newsletter',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFFF6719)),
          useMaterial3: true,
        ),
        routerConfig: _router,
      ),
    );
  }
}

final _router = GoRouter(
  routes: [
    GoRoute(path: '/', builder: (_, __) => const PostListScreen()),
    GoRoute(path: '/editor', builder: (_, __) => const PostEditorScreen()),
    GoRoute(path: '/subscribers', builder: (_, __) => const SubscriberListScreen()),
  ],
);

class PostListScreen extends StatelessWidget {
  const PostListScreen({super.key});

  static const _query = r'query { np_posts(where: {status: {_eq: "published"}}, order_by: {published_at: desc}) { id title subtitle published_at } }';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Newsletter'),
        actions: [
          IconButton(icon: const Icon(Icons.edit), onPressed: () => context.go('/editor')),
          IconButton(icon: const Icon(Icons.people), onPressed: () => context.go('/subscribers')),
        ],
      ),
      body: Query(
        options: QueryOptions(document: gql(_query)),
        builder: (result, {fetchMore, refetch}) {
          if (result.isLoading) return const Center(child: CircularProgressIndicator());
          final posts = result.data?['np_posts'] as List? ?? [];
          return ListView.builder(
            itemCount: posts.length,
            itemBuilder: (ctx, i) {
              final p = posts[i] as Map<String, dynamic>;
              return ListTile(
                title: Text(p['title'] as String),
                subtitle: Text(p['subtitle'] as String? ?? ''),
              );
            },
          );
        },
      ),
    );
  }
}

class PostEditorScreen extends StatelessWidget {
  const PostEditorScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('New Post')),
      body: const Center(child: Text('Post editor goes here')),
    );
  }
}

class SubscriberListScreen extends StatelessWidget {
  const SubscriberListScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Subscribers')),
      body: const Center(child: Text('Subscriber list goes here')),
    );
  }
}
