// Package monitoring — alert rule and Alertmanager config generators.
//
// This file owns the generation of:
//   - otel-alerts.yml  — Prometheus alert rules for OTEL Collector + Tempo
//   - alertmanager.yml — Alertmanager routing and receiver configuration
//
// Both files are written into the target project's monitoring/ directory by
// nself build when MONITORING_ENABLED=true and MONITORING_TRACING_ENABLED=true.
package monitoring

import (
	"bytes"
	"fmt"
	"text/template"
)

// AlertReceiver defines an Alertmanager notification receiver.
type AlertReceiver struct {
	// Name is the receiver identifier referenced by routing rules.
	Name string
	// EmailTo is the address to send alerts to when this receiver fires.
	// Reads ALERTMANAGER_ONCALL_EMAIL at runtime when empty.
	EmailTo string
	// IsOncallStub marks this receiver as the P97 interim email stub.
	// P98 will replace it with a PagerDuty/Opsgenie integration.
	IsOncallStub bool
}

// AlertmanagerConfig captures everything needed to render alertmanager.yml.
type AlertmanagerConfig struct {
	// SMTPHost is the SMTP relay host:port for email notifications.
	SMTPHost string
	// SMTPFrom is the envelope-from address.
	SMTPFrom string
	// Receivers is the list of notification receivers.
	Receivers []AlertReceiver
	// GroupWait is how long Alertmanager buffers alerts before sending the
	// first notification. Default: 30s.
	GroupWait string
	// GroupInterval is the interval between notifications for the same group.
	// Default: 5m.
	GroupInterval string
	// RepeatInterval is the interval before re-sending a resolved or ongoing
	// alert. Default: 4h.
	RepeatInterval string
}

// DefaultAlertmanagerConfig returns nSelf's out-of-the-box Alertmanager
// settings: email oncall-stub receiver for critical, warning routes to null.
func DefaultAlertmanagerConfig() *AlertmanagerConfig {
	return &AlertmanagerConfig{
		SMTPHost:       "${ALERTMANAGER_SMTP_HOST:-localhost:25}",
		SMTPFrom:       "${ALERTMANAGER_SMTP_FROM:-alertmanager@nself.org}",
		GroupWait:      "30s",
		GroupInterval:  "5m",
		RepeatInterval: "4h",
		Receivers: []AlertReceiver{
			{
				Name:         "oncall-stub",
				EmailTo:      "${ALERTMANAGER_ONCALL_EMAIL:-support@nself.org}",
				IsOncallStub: true,
			},
			{
				Name: "null-receiver",
			},
		},
	}
}

const alertmanagerTmpl = `# Generated by nself build — DO NOT HAND EDIT
# Alertmanager configuration for the nSelf monitoring stack.
# Routing: severity=critical → oncall-stub (email); severity=warning → null-receiver (log only).
#
# P98: replace oncall-stub with PagerDuty/Opsgenie when an on-call rotation is established.
# See cli/monitoring/runbooks/ for per-alert runbooks.

global:
  smtp_smarthost: {{.SMTPHost}}
  smtp_from: {{.SMTPFrom}}
  smtp_require_tls: false

route:
  receiver: null-receiver
  group_by: [alertname, job]
  group_wait: {{.GroupWait}}
  group_interval: {{.GroupInterval}}
  repeat_interval: {{.RepeatInterval}}
  routes:
    - matchers:
        - severity = critical
      receiver: oncall-stub
      continue: false
    - matchers:
        - severity = warning
      receiver: null-receiver
      continue: false

receivers:
{{- range .Receivers}}
  - name: {{.Name}}
{{- if .EmailTo}}
    email_configs:
      - to: {{.EmailTo}}
        send_resolved: true
{{- if .IsOncallStub}}
        # P98: replace with PagerDuty/Opsgenie integration when on-call rotation exists.
{{- end}}
{{- end}}
{{- end}}

inhibit_rules:
  # Silence all warnings when a critical alert is already firing for the same job.
  - source_matchers:
      - severity = critical
    target_matchers:
      - severity = warning
    equal: [job]
`

// RenderAlertmanagerYAML returns the rendered alertmanager.yml bytes for cfg.
func RenderAlertmanagerYAML(cfg *AlertmanagerConfig) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("monitoring: nil AlertmanagerConfig")
	}
	tmpl, err := template.New("alertmanager").Parse(alertmanagerTmpl)
	if err != nil {
		return nil, fmt.Errorf("monitoring: parse alertmanager template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return nil, fmt.Errorf("monitoring: execute alertmanager template: %w", err)
	}
	return buf.Bytes(), nil
}

// OTELAlertRulesConfig carries parameterised thresholds for the OTEL alert
// rules file. Callers may override these to tighten or relax alert sensitivity.
type OTELAlertRulesConfig struct {
	// SpanIngestDropRatio is the fraction below which the 5m span ingest rate
	// must fall relative to the 30m baseline to trigger OtelSpanIngestDrop.
	// Default: 0.5 (50% drop).
	SpanIngestDropRatio float64
	// DownDuration is the minimum time a target must be absent before the
	// OtelCollectorDown / TempoDown alerts fire. Default: 5m.
	DownDuration string
	// SpanDropDuration is the minimum time the span ingest ratio must be low
	// before OtelSpanIngestDrop fires. Default: 10m.
	SpanDropDuration string
	// ExportErrorDuration is the minimum time export errors must persist before
	// TempoScrapeErrors fires. Default: 5m.
	ExportErrorDuration string
}

// DefaultOTELAlertRulesConfig returns conservative nSelf defaults: 50% span
// drop triggers a warning after 10 minutes; down alerts after 5 minutes.
func DefaultOTELAlertRulesConfig() *OTELAlertRulesConfig {
	return &OTELAlertRulesConfig{
		SpanIngestDropRatio: 0.5,
		DownDuration:        "5m",
		SpanDropDuration:    "10m",
		ExportErrorDuration: "5m",
	}
}

const otelAlertsTmpl = `# Generated by nself build — DO NOT HAND EDIT
# Prometheus alert rules for the OTEL Collector and Tempo tracing backend.
# These rules apply when MONITORING_TRACING_ENABLED=true.
#
# Runbooks:
#   OtelCollectorDown  → monitoring/runbooks/otel-collector-down.md
#   TempoDown          → monitoring/runbooks/tempo-down.md
#   OtelSpanIngestDrop → monitoring/runbooks/otel-collector-down.md
#   TempoScrapeErrors  → monitoring/runbooks/tempo-down.md

groups:
  - name: otel_tracing
    rules:

      # CRITICAL: OTEL Collector is unreachable by Prometheus.
      # All spans from instrumented services are lost while this fires.
      # Runbook: monitoring/runbooks/otel-collector-down.md
      - alert: OtelCollectorDown
        expr: up{job="otelcol"} == 0
        for: {{.DownDuration}}
        labels:
          severity: critical
        annotations:
          summary: "OTEL Collector is down"
          description: >
            The OTEL Collector (job=otelcol) has been unreachable for {{ "{{" }} $value {{ "}}" }} seconds.
            All distributed traces are lost until the collector recovers.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-OTEL-Collector-Down"

      # CRITICAL: Tempo tracing backend is unreachable.
      # Existing traces are preserved in storage; new spans cannot be stored.
      # Runbook: monitoring/runbooks/tempo-down.md
      - alert: TempoDown
        expr: up{job="tempo"} == 0
        for: {{.DownDuration}}
        labels:
          severity: critical
        annotations:
          summary: "Tempo tracing backend is down"
          description: >
            Tempo (job=tempo) has been unreachable for {{ "{{" }} $value {{ "}}" }} seconds.
            New spans cannot be stored. Existing traces are safe in on-disk storage.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-Tempo-Down"

      # WARNING: Span ingest rate has dropped more than {{.SpanIngestDropRatio | printf "%.0f%%"}} below the 30-minute baseline.
      # May indicate: collector congestion, exporter backpressure, or application instrumentation failure.
      # Runbook: monitoring/runbooks/otel-collector-down.md
      - alert: OtelSpanIngestDrop
        expr: >
          rate(otelcol_receiver_accepted_spans_total[5m])
          < {{.SpanIngestDropRatio}} * rate(otelcol_receiver_accepted_spans_total[30m])
        for: {{.SpanDropDuration}}
        labels:
          severity: warning
        annotations:
          summary: "OTEL span ingest rate dropped >{{.SpanIngestDropRatio | printf "%.0f%%"}}"
          description: >
            The 5-minute span acceptance rate has been below
            {{.SpanIngestDropRatio | printf "%.0f%%"}} of the 30-minute baseline
            for {{ "{{" }} $labels.job {{ "}}" }}. Check for exporter back-pressure or
            application instrumentation issues.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-OTEL-Collector-Down"

      # WARNING: OTEL Collector is failing to export spans to Tempo.
      # Spans are buffered in memory; prolonged failure causes data loss.
      # Runbook: monitoring/runbooks/tempo-down.md
      - alert: TempoScrapeErrors
        expr: rate(otelcol_exporter_send_failed_spans_total[5m]) > 0
        for: {{.ExportErrorDuration}}
        labels:
          severity: warning
        annotations:
          summary: "OTEL Collector exporting spans to Tempo is failing"
          description: >
            The OTEL Collector has been failing to send spans to Tempo for
            {{ "{{" }} $value {{ "}}" }} failed span/s over the last 5 minutes.
            Spans are buffered in memory and will be lost if the collector restarts.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-Tempo-Down"
`

// RenderOTELAlertsYAML returns the rendered otel-alerts.yml bytes for cfg.
func RenderOTELAlertsYAML(cfg *OTELAlertRulesConfig) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("monitoring: nil OTELAlertRulesConfig")
	}
	funcMap := template.FuncMap{
		"printf": fmt.Sprintf,
	}
	tmpl, err := template.New("otel-alerts").Funcs(funcMap).Parse(otelAlertsTmpl)
	if err != nil {
		return nil, fmt.Errorf("monitoring: parse otel-alerts template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return nil, fmt.Errorf("monitoring: execute otel-alerts template: %w", err)
	}
	return buf.Bytes(), nil
}
