package monitoring

import (
	"bytes"
	"fmt"
	"text/template"
)

// LokiConfig captures the fields needed to render loki.yml.
type LokiConfig struct {
	// RetentionPeriod is how long logs are kept. Loki accepts Go-style
	// durations (e.g. "720h" = 30d, "2160h" = 90d).
	RetentionPeriod string
	// MaxChunkAge caps how long a chunk can stay open before forced flush.
	MaxChunkAge string
	// MultiTenantEnabled, when true, runs Loki in multi-tenant mode with
	// per-tenant isolation. Each nSelf project becomes a tenant.
	MultiTenantEnabled bool
	// RuleEngineEnabled turns on the Loki rule engine for log-based alerts.
	RuleEngineEnabled bool
}

// DefaultLokiConfig returns the settings nSelf uses out of the box: 30-day
// retention (720h), single-tenant, rule engine on. Retention was extended from
// 168h (7d) to 720h (30d) in S224 to satisfy production debugging requirements.
func DefaultLokiConfig() *LokiConfig {
	return &LokiConfig{
		RetentionPeriod:    "720h",
		MaxChunkAge:        "1h",
		MultiTenantEnabled: false,
		RuleEngineEnabled:  true,
	}
}

const lokiTmpl = `# Generated by nself build — DO NOT HAND EDIT
auth_enabled: {{if .MultiTenantEnabled}}true{{else}}false{{end}}

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 5m
  chunk_target_size: 1048576
  max_chunk_age: {{.MaxChunkAge}}
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: {{.RetentionPeriod}}
  max_query_series: 5000
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30
{{- if .MultiTenantEnabled}}
  # Per-tenant overrides live in /etc/loki/overrides.yml
  per_tenant_override_config: /etc/loki/overrides.yml
{{- end}}

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

{{- if .RuleEngineEnabled}}

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules-tmp
  rule_path: /loki/rules-tmp
  ring:
    kvstore:
      store: inmemory
  enable_api: true
{{- end}}

analytics:
  reporting_enabled: false
`

// RenderLokiYAML returns loki.yml bytes for cfg.
func RenderLokiYAML(cfg *LokiConfig) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("monitoring: nil LokiConfig")
	}
	tmpl, err := template.New("loki").Parse(lokiTmpl)
	if err != nil {
		return nil, fmt.Errorf("monitoring: parse loki template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return nil, fmt.Errorf("monitoring: execute loki template: %w", err)
	}
	return buf.Bytes(), nil
}

// PromtailConfig captures the fields needed to render promtail.yml. Promtail
// reads Docker container logs and ships them to Loki with labels that let
// Grafana filter by plugin, tenant, and service.
type PromtailConfig struct {
	// LokiURL is the Loki push endpoint. Inside the docker network this is
	// typically "http://loki:3100/loki/api/v1/push".
	LokiURL string
	// TenantID is the X-Scope-OrgID sent with every push. Empty in
	// single-tenant mode; required when Loki is multi-tenant.
	TenantID string
	// ProjectName is the nSelf project name; attached as a static label on
	// every line so operators can distinguish multiple projects on one host.
	ProjectName string
}

// DefaultPromtailConfig returns the settings nSelf uses out of the box.
func DefaultPromtailConfig(projectName string) *PromtailConfig {
	return &PromtailConfig{
		LokiURL:     "http://loki:3100/loki/api/v1/push",
		ProjectName: projectName,
	}
}

const promtailTmpl = `# Generated by nself build — DO NOT HAND EDIT
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: {{.LokiURL}}
{{- if .TenantID}}
    tenant_id: {{.TenantID}}
{{- end}}

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
        filters:
          - name: label
            values: ["com.docker.compose.project"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      - source_labels: ['__meta_docker_container_label_nself_plugin']
        target_label: 'plugin'
      - source_labels: ['__meta_docker_container_label_nself_tier']
        target_label: 'tier'
    pipeline_stages:
      - docker: {}
      - labels:
          container:
          service:
          project:
          plugin:
          tier:
      - static_labels:
          nself_project: {{.ProjectName}}
`

// RenderPromtailYAML returns promtail.yml bytes for cfg.
func RenderPromtailYAML(cfg *PromtailConfig) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("monitoring: nil PromtailConfig")
	}
	tmpl, err := template.New("promtail").Parse(promtailTmpl)
	if err != nil {
		return nil, fmt.Errorf("monitoring: parse promtail template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return nil, fmt.Errorf("monitoring: execute promtail template: %w", err)
	}
	return buf.Bytes(), nil
}
