package monitoring

// Purpose: generation of otel-alerts.yml — Prometheus alert rules for OTEL Collector + Tempo, written by nself build when MONITORING_TRACING_ENABLED=true.
// Inputs: an OTELAlertRulesConfig with parameterised thresholds (span-ingest drop ratio, latency, etc.).
// Outputs: rendered YAML bytes for otel-alerts.yml.
// Constraints: split out of alerts.go as a pure move (CLI-R12); no behavior change. See alerts.go's package doc for the full on-call integration contract shared with the Alertmanager side.

import (
	"bytes"
	"fmt"
	"text/template"
)

// OTELAlertRulesConfig carries parameterised thresholds for the OTEL alert
// rules file. Callers may override these to tighten or relax alert sensitivity.
type OTELAlertRulesConfig struct {
	// SpanIngestDropRatio is the fraction below which the 5m span ingest rate
	// must fall relative to the 30m baseline to trigger OtelSpanIngestDrop.
	// Default: 0.5 (50% drop).
	SpanIngestDropRatio float64
	// DownDuration is the minimum time a target must be absent before the
	// OtelCollectorDown / TempoDown alerts fire. Default: 5m.
	DownDuration string
	// SpanDropDuration is the minimum time the span ingest ratio must be low
	// before OtelSpanIngestDrop fires. Default: 10m.
	SpanDropDuration string
	// ExportErrorDuration is the minimum time export errors must persist before
	// TempoScrapeErrors fires. Default: 5m.
	ExportErrorDuration string
}

// DefaultOTELAlertRulesConfig returns conservative nSelf defaults: 50% span
// drop triggers a warning after 10 minutes; down alerts after 5 minutes.
func DefaultOTELAlertRulesConfig() *OTELAlertRulesConfig {
	return &OTELAlertRulesConfig{
		SpanIngestDropRatio: 0.5,
		DownDuration:        "5m",
		SpanDropDuration:    "10m",
		ExportErrorDuration: "5m",
	}
}

const otelAlertsTmpl = `# Generated by nself build — DO NOT HAND EDIT
# Prometheus alert rules for the OTEL Collector and Tempo tracing backend.
# These rules apply when MONITORING_TRACING_ENABLED=true.
#
# Runbooks:
#   OtelCollectorDown  → monitoring/runbooks/otel-collector-down.md
#   TempoDown          → monitoring/runbooks/tempo-down.md
#   OtelSpanIngestDrop → monitoring/runbooks/otel-collector-down.md
#   TempoScrapeErrors  → monitoring/runbooks/tempo-down.md

groups:
  - name: otel_tracing
    rules:

      # CRITICAL: OTEL Collector is unreachable by Prometheus.
      # All spans from instrumented services are lost while this fires.
      # Runbook: monitoring/runbooks/otel-collector-down.md
      - alert: OtelCollectorDown
        expr: up{job="otelcol"} == 0
        for: {{.DownDuration}}
        labels:
          severity: critical
        annotations:
          summary: "OTEL Collector is down"
          description: >
            The OTEL Collector (job=otelcol) has been unreachable for {{ "{{" }} $value {{ "}}" }} seconds.
            All distributed traces are lost until the collector recovers.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-OTEL-Collector-Down"

      # CRITICAL: Tempo tracing backend is unreachable.
      # Existing traces are preserved in storage; new spans cannot be stored.
      # Runbook: monitoring/runbooks/tempo-down.md
      - alert: TempoDown
        expr: up{job="tempo"} == 0
        for: {{.DownDuration}}
        labels:
          severity: critical
        annotations:
          summary: "Tempo tracing backend is down"
          description: >
            Tempo (job=tempo) has been unreachable for {{ "{{" }} $value {{ "}}" }} seconds.
            New spans cannot be stored. Existing traces are safe in on-disk storage.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-Tempo-Down"

      # WARNING: Span ingest rate has dropped more than {{.SpanIngestDropRatio | printf "%.0f%%"}} below the 30-minute baseline.
      # May indicate: collector congestion, exporter backpressure, or application instrumentation failure.
      # Runbook: monitoring/runbooks/otel-collector-down.md
      - alert: OtelSpanIngestDrop
        expr: >
          rate(otelcol_receiver_accepted_spans_total[5m])
          < {{.SpanIngestDropRatio}} * rate(otelcol_receiver_accepted_spans_total[30m])
        for: {{.SpanDropDuration}}
        labels:
          severity: warning
        annotations:
          summary: "OTEL span ingest rate dropped >{{.SpanIngestDropRatio | printf "%.0f%%"}}"
          description: >
            The 5-minute span acceptance rate has been below
            {{.SpanIngestDropRatio | printf "%.0f%%"}} of the 30-minute baseline
            for {{ "{{" }} $labels.job {{ "}}" }}. Check for exporter back-pressure or
            application instrumentation issues.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-OTEL-Collector-Down"

      # WARNING: OTEL Collector is failing to export spans to Tempo.
      # Spans are buffered in memory; prolonged failure causes data loss.
      # Runbook: monitoring/runbooks/tempo-down.md
      - alert: TempoScrapeErrors
        expr: rate(otelcol_exporter_send_failed_spans_total[5m]) > 0
        for: {{.ExportErrorDuration}}
        labels:
          severity: warning
        annotations:
          summary: "OTEL Collector exporting spans to Tempo is failing"
          description: >
            The OTEL Collector has been failing to send spans to Tempo for
            {{ "{{" }} $value {{ "}}" }} failed span/s over the last 5 minutes.
            Spans are buffered in memory and will be lost if the collector restarts.
          runbook_url: "https://github.com/nself-org/cli/wiki/Runbook-Tempo-Down"
`

// RenderOTELAlertsYAML returns the rendered otel-alerts.yml bytes for cfg.
func RenderOTELAlertsYAML(cfg *OTELAlertRulesConfig) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("monitoring: nil OTELAlertRulesConfig")
	}
	funcMap := template.FuncMap{
		"printf": fmt.Sprintf,
	}
	tmpl, err := template.New("otel-alerts").Funcs(funcMap).Parse(otelAlertsTmpl)
	if err != nil {
		return nil, fmt.Errorf("monitoring: parse otel-alerts template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return nil, fmt.Errorf("monitoring: execute otel-alerts template: %w", err)
	}
	return buf.Bytes(), nil
}
