import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:go_router/go_router.dart';

// zoom-clone starter — generated by nself init --template zoom-clone

const _hasuraEndpoint = String.fromEnvironment(
  'HASURA_GRAPHQL_URL',
  defaultValue: 'http://localhost:8080/v1/graphql',
);

void main() async {
  await initHiveForFlutter();
  runApp(const ZoomCloneApp());
}

class ZoomCloneApp extends StatelessWidget {
  const ZoomCloneApp({super.key});

  @override
  Widget build(BuildContext context) {
    final client = ValueNotifier(
      GraphQLClient(
        link: HttpLink(_hasuraEndpoint),
        cache: GraphQLCache(store: HiveStore()),
      ),
    );
    return GraphQLProvider(
      client: client,
      child: MaterialApp.router(
        title: 'Video Meetings',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF2D8CFF)),
          useMaterial3: true,
        ),
        routerConfig: _router,
      ),
    );
  }
}

final _router = GoRouter(
  routes: [
    GoRoute(path: '/', builder: (_, __) => const MeetingLobbyScreen()),
    GoRoute(path: '/meeting/:id', builder: (ctx, state) => VideoGridScreen(meetingId: state.pathParameters['id']!)),
    GoRoute(path: '/recordings', builder: (_, __) => const RecordingPlaybackScreen()),
  ],
);

class MeetingLobbyScreen extends StatelessWidget {
  const MeetingLobbyScreen({super.key});

  static const _query = r'query { np_meetings(order_by: {scheduled_at: desc}, limit: 20) { id title status scheduled_at meeting_code } }';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Meetings'),
        actions: [
          IconButton(icon: const Icon(Icons.video_library), onPressed: () => context.go('/recordings')),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {},
        icon: const Icon(Icons.videocam),
        label: const Text('New Meeting'),
      ),
      body: Query(
        options: QueryOptions(document: gql(_query)),
        builder: (result, {fetchMore, refetch}) {
          if (result.isLoading) return const Center(child: CircularProgressIndicator());
          final meetings = result.data?['np_meetings'] as List? ?? [];
          return ListView.builder(
            itemCount: meetings.length,
            itemBuilder: (ctx, i) {
              final m = meetings[i] as Map<String, dynamic>;
              return ListTile(
                title: Text(m['title'] as String),
                subtitle: Text('Code: ${m['meeting_code']} — ${m['status']}'),
                trailing: const Icon(Icons.arrow_forward_ios, size: 16),
                onTap: () => ctx.go('/meeting/${m['id']}'),
              );
            },
          );
        },
      ),
    );
  }
}

class VideoGridScreen extends StatelessWidget {
  final String meetingId;
  const VideoGridScreen({super.key, required this.meetingId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Meeting')),
      body: Center(child: Text('Video grid for meeting $meetingId')),
    );
  }
}

class RecordingPlaybackScreen extends StatelessWidget {
  const RecordingPlaybackScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Recordings')),
      body: const Center(child: Text('Recording list goes here')),
    );
  }
}
