// Package domain provides DNS propagation polling and nginx server block
// generation for custom domain provisioning.
package domain

import (
	"context"
	"fmt"
	"net"
	"strings"
	"time"
)

// DNSRecord describes a required DNS record for domain verification.
type DNSRecord struct {
	Type  string // A, CNAME, AAAA
	Name  string // hostname
	Value string // IP or target
}

// RequiredRecords returns the DNS records a user must create for a custom domain.
func RequiredRecords(domain, serverIP string) []DNSRecord {
	return []DNSRecord{
		{Type: "A", Name: domain, Value: serverIP},
	}
}

// PollDNS checks whether the domain resolves to the expected IP address.
// It polls every interval until the context is cancelled or the domain resolves.
// Returns nil on success, context.DeadlineExceeded on timeout.
func PollDNS(ctx context.Context, domain, expectedIP string, interval time.Duration) error {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C:
			ips, err := net.LookupHost(domain)
			if err != nil {
				continue // DNS not yet propagated.
			}
			for _, ip := range ips {
				if ip == expectedIP {
					return nil
				}
			}
		}
	}
}

// NginxServerBlock generates an nginx server block configuration for a custom domain.
func NginxServerBlock(domain, upstream, sslDir string, hasSSL bool) string {
	var sb strings.Builder

	sb.WriteString("# Custom domain: " + domain + "\n")
	sb.WriteString("# Generated by nself ssl add\n\n")
	sb.WriteString("server {\n")

	if hasSSL {
		sb.WriteString("    listen 443 ssl;\n")
		sb.WriteString("    listen [::]:443 ssl;\n")
		sb.WriteString("    http2 on;\n")
	} else {
		sb.WriteString("    listen 80;\n")
		sb.WriteString("    listen [::]:80;\n")
	}

	sb.WriteString(fmt.Sprintf("    server_name %s;\n", domain))

	if hasSSL {
		sb.WriteString(fmt.Sprintf("\n    ssl_certificate /etc/letsencrypt/live/%s/fullchain.pem;\n", domain))
		sb.WriteString(fmt.Sprintf("    ssl_certificate_key /etc/letsencrypt/live/%s/privkey.pem;\n", domain))
		sb.WriteString("\n    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains; preload\" always;\n")
	}

	sb.WriteString(`
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "0" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    server_tokens off;

    location / {
        resolver 127.0.0.11 valid=10s;
        set $upstream http://` + upstream + `;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
`)

	return sb.String()
}
