package doctor

// dogfood_deps_sport.go — vendor license scan (VENDOR-DEP-01) and per-subapp
// sport.json sync check (DOGFOOD-SUBAPPS-01), split out of dogfood_checks.go
// (CLI-R12) as a pure move.
//
// Inputs: a context (unused by checkAGPLDeps directly, kept for signature
// consistency with the other dogfood checks) and the project directory.
// Outputs: a single CheckResult (checkAGPLDeps) or one per subapp
// (checkSubappSportSync).
// Constraints: depends on dogfoodSubapps, defined in dogfood_checks.go.

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
)

// agplLicenseRegex matches license fields in package.json files for AGPL/SSPL/CC-BY-NC.
// Production source must not depend on AGPL/SSPL because those copyleft terms
// would force release of nSelf's own source.
var agplLicenseRegex = regexp.MustCompile(`(?i)"license"\s*:\s*"(AGPL|SSPL|CC-BY-NC)`)

// checkAGPLDeps walks the project's vendored / node_modules-style dependency
// metadata for AGPL/SSPL license declarations. It does NOT do a full SBOM scan
// (that's `nself license-audit`) — this is a fast, last-line gate for prod source.
func checkAGPLDeps(ctx context.Context, projectDir string) CheckResult {
	const checkName = "VENDOR-DEP-01: no AGPL/SSPL deps"

	// Look at common Go and Node dep manifests in the project.
	candidates := []string{
		filepath.Join(projectDir, "go.mod"),
		filepath.Join(projectDir, "package.json"),
		filepath.Join(projectDir, "vendor", "modules.txt"),
		filepath.Join(projectDir, "pnpm-lock.yaml"),
	}

	scanned := 0
	for _, path := range candidates {
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		scanned++
		if agplLicenseRegex.Find(data) != nil {
			// Don't expose the offending line directly — it could leak proprietary
			// names. Tell the operator to run the full license-audit instead.
			return CheckResult{Section: "security", Name: checkName, Status: "fail",
				Message: fmt.Sprintf("AGPL/SSPL/CC-BY-NC license declaration found in %s", filepath.Base(path)),
				FixCmd:  "run: nself license-audit  # for full report and remediation"}
		}
	}

	if scanned == 0 {
		return CheckResult{Section: "security", Name: checkName, Status: "pass",
			Message: "no dependency manifests found (skipped)"}
	}
	return CheckResult{Section: "security", Name: checkName, Status: "pass",
		Message: fmt.Sprintf("scanned %d manifest(s); no AGPL/SSPL/CC-BY-NC", scanned)}
}

// checkSubappSportSync verifies every dogfood subapp directory has a
// synced sport.json (generated by web/org/scripts/sync-sport.mjs at build).
// Missing or stale sport.json means marketing/docs are out of sync with code.
func checkSubappSportSync(projectDir string) []CheckResult {
	var results []CheckResult
	for _, name := range dogfoodSubapps {
		// Skip "backend" — it's not a subapp with a sport.json.
		if name == "backend" {
			continue
		}
		checkName := fmt.Sprintf("DOGFOOD-SUBAPPS-01: sport.json on %s", name)
		// Most likely paths: web/<app>/sport.json or web/<app>/src/sport.json
		// or web/<app>/public/sport.json. Look up all three.
		candidates := []string{
			filepath.Join(projectDir, name, "sport.json"),
			filepath.Join(projectDir, name, "src", "sport.json"),
			filepath.Join(projectDir, name, "public", "sport.json"),
		}
		found := ""
		for _, p := range candidates {
			if info, err := os.Stat(p); err == nil && !info.IsDir() {
				found = p
				break
			}
		}
		if found == "" {
			results = append(results, CheckResult{
				Section: "dogfood", Name: checkName, Status: "warn",
				Message: "sport.json not found",
				FixCmd:  "run: pnpm --filter " + name + " run sync-sport",
			})
			continue
		}
		results = append(results, CheckResult{
			Section: "dogfood", Name: checkName, Status: "pass",
			Message: filepath.Base(found) + " present",
		})
	}
	return results
}
