// S12.T01 — unit tests for OBS-SCRAPE-01 doctor check.
package doctor

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

// makePluginManifest writes a minimal plugin.json under pluginDir/<name>/.
func makePluginManifest(t *testing.T, pluginDir, name string) {
	t.Helper()
	dir := filepath.Join(pluginDir, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", dir, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "plugin.json"), []byte(`{"name":"`+name+`","version":"1.0.0"}`), 0o644); err != nil {
		t.Fatalf("write manifest: %v", err)
	}
}

// TestCheckOBSScrape_NoPluginsInstalled: no ɳSentry plugins → pass (skipped).
func TestCheckOBSScrape_NoPluginsInstalled(t *testing.T) {
	projectDir := t.TempDir()
	pluginDir := t.TempDir()

	r := CheckOBSScrape(context.Background(), projectDir, pluginDir)
	if r.Status != "pass" {
		t.Errorf("no plugins: want pass, got %q (%s)", r.Status, r.Message)
	}
}

// TestCheckOBSScrape_InstalledWithMissingYAML: plugins installed but
// monitoring/prometheus.yml absent → warn.
func TestCheckOBSScrape_InstalledWithMissingYAML(t *testing.T) {
	projectDir := t.TempDir()
	pluginDir := t.TempDir()
	makePluginManifest(t, pluginDir, "nself-uptime-monitor")

	r := CheckOBSScrape(context.Background(), projectDir, pluginDir)
	if r.Status != "warn" {
		t.Errorf("plugins installed, no yaml: want warn, got %q (%s)", r.Status, r.Message)
	}
	if r.FixCmd != "nself build" {
		t.Errorf("expected FixCmd=nself build, got %q", r.FixCmd)
	}
}

// TestCheckOBSScrape_InstalledWithCompleteYAML: plugins installed and
// prometheus.yml contains all expected job_name lines → pass.
func TestCheckOBSScrape_InstalledWithCompleteYAML(t *testing.T) {
	projectDir := t.TempDir()
	pluginDir := t.TempDir()
	makePluginManifest(t, pluginDir, "nself-uptime-monitor")
	makePluginManifest(t, pluginDir, "nself-status-page")

	monDir := filepath.Join(projectDir, "monitoring")
	if err := os.MkdirAll(monDir, 0o755); err != nil {
		t.Fatalf("mkdir monitoring: %v", err)
	}
	yamlBody := `# Generated by nself build
scrape_configs:
  - job_name: nsentry-uptime-monitor
    static_configs:
      - targets:
          - nself-uptime-monitor:3831
  - job_name: nsentry-status-page
    static_configs:
      - targets:
          - nself-status-page:3832
`
	if err := os.WriteFile(filepath.Join(monDir, "prometheus.yml"), []byte(yamlBody), 0o644); err != nil {
		t.Fatalf("write yaml: %v", err)
	}

	r := CheckOBSScrape(context.Background(), projectDir, pluginDir)
	if r.Status != "pass" {
		t.Errorf("complete yaml: want pass, got %q (%s)", r.Status, r.Message)
	}
}

// TestCheckOBSScrape_InstalledButYAMLMissingSomeJobs: 2 plugins installed,
// only 1 job present in yaml → warn naming the missing slug.
func TestCheckOBSScrape_InstalledButYAMLMissingSomeJobs(t *testing.T) {
	projectDir := t.TempDir()
	pluginDir := t.TempDir()
	makePluginManifest(t, pluginDir, "nself-uptime-monitor")
	makePluginManifest(t, pluginDir, "nself-rum")

	monDir := filepath.Join(projectDir, "monitoring")
	if err := os.MkdirAll(monDir, 0o755); err != nil {
		t.Fatalf("mkdir monitoring: %v", err)
	}
	// Only uptime-monitor present, rum missing.
	yamlBody := `scrape_configs:
  - job_name: nsentry-uptime-monitor
`
	if err := os.WriteFile(filepath.Join(monDir, "prometheus.yml"), []byte(yamlBody), 0o644); err != nil {
		t.Fatalf("write yaml: %v", err)
	}

	r := CheckOBSScrape(context.Background(), projectDir, pluginDir)
	if r.Status != "warn" {
		t.Errorf("partial yaml: want warn, got %q", r.Status)
	}
	if !contains(r.Message, "rum") {
		t.Errorf("expected 'rum' to appear in missing list, got %q", r.Message)
	}
	if r.FixCmd != "nself build" {
		t.Errorf("expected FixCmd=nself build, got %q", r.FixCmd)
	}
}

// contains: small helper, avoids dragging strings.Contains into the test
// declarations and keeps the test file self-contained.
func contains(haystack, needle string) bool {
	for i := 0; i+len(needle) <= len(haystack); i++ {
		if haystack[i:i+len(needle)] == needle {
			return true
		}
	}
	return false
}
