// Purpose:     render the parity matrix as committed markdown + JSON.
// Inputs:      the scored []Row from buildMatrix.
// Outputs:     renderMarkdown returns the full .github/surface-parity.md
//
//	content (with the GENERATED BY header and column-rule notes);
//	renderJSON returns the .github/surface-parity.json bytes.
//
// Constraints: both must be pure functions of rows (no timestamps, no
//
//	non-deterministic map iteration) so two runs against the same
//	source produce byte-identical output — required by
//	internal/repoqa's drift test and by the idempotency requirement
//	in the CLI-R17 ticket.
package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const generatedHeader = "<!-- GENERATED BY tools/parity — DO NOT HAND EDIT. Run `make parity`. -->"

func renderMarkdown(rows []Row) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n\n# Four-Surface Parity Matrix\n\n")
	b.WriteString("One row per top-level command (CLI-R17), scored against the four surfaces " +
		"a command can ship on. The wiki column is a hard CI gate; the other three are " +
		"informational — see the matching-rule comments in tools/parity/ for exactly how " +
		"each column is decided and why it may under-count.\n\n")

	b.WriteString("**OpenAPI Route** is always `n/a`: this repo has no route source to check " +
		"against (no `internal/apidocs`, no `openapi.go` anywhere in the tree as of CLI-R17). " +
		"If that changes, wire a real check here instead of inventing data.\n\n")

	b.WriteString("**Env Vars** reflects only direct `os.Getenv`/`viper.Get*` calls in the " +
		"command's own `cmd/commands/<name>*.go` files — env vars read through internal/* " +
		"packages are invisible to this check and will show `n/a` even when the command " +
		"does read documented vars. See tools/parity/envvars.go for the full rule.\n\n")

	b.WriteString("**MCP Tool** credits exact token matches only (e.g. `nself_doctor` -> `doctor`); " +
		"near-misses like `nself_run_migration` vs. `migrate` are not credited. " +
		"See tools/parity/mcptools.go for the full rule.\n\n")

	b.WriteString("| Command | Group | Wiki Page | MCP Tool | Env Vars | OpenAPI Route |\n")
	b.WriteString("|---|---|---|---|---|---|\n")

	var missingWiki, missingMCP, undocEnv int
	for _, r := range rows {
		group := r.GroupID
		if group == "" {
			group = "—"
		}
		wiki := checkmark(r.WikiPage)
		if !r.WikiPage {
			missingWiki++
		}
		mcp := checkmark(r.MCPTool)
		if !r.MCPTool {
			missingMCP++
		}
		if strings.HasPrefix(r.EnvVars, "undocumented") {
			undocEnv++
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n",
			r.Path, group, wiki, mcp, r.EnvVars, r.OpenAPI)
	}

	fmt.Fprintf(&b, "\nTotal: %d commands. Missing wiki page: %d. No MCP tool: %d. "+
		"Env vars found but undocumented: %d.\n", len(rows), missingWiki, missingMCP, undocEnv)

	return b.String()
}

func checkmark(ok bool) string {
	if ok {
		return "yes"
	}
	return "no"
}

func renderJSON(rows []Row) ([]byte, error) {
	doc := struct {
		Generated string `json:"generated_by"`
		Rows      []Row  `json:"rows"`
	}{
		Generated: "tools/parity",
		Rows:      rows,
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}
