name: Sync docs to Wiki

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/sync-wiki.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check if Wiki is enabled
        id: wiki-check
        run: |
          # Try to clone wiki with authentication
          WIKI_URL="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git"
          if git clone "$WIKI_URL" wiki 2>/dev/null; then
            echo "wiki_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Wiki is enabled and accessible"
          else
            echo "wiki_exists=false" >> $GITHUB_OUTPUT
            echo "::notice::Wiki not enabled or not accessible. To sync docs to wiki, enable it in Settings → Features → Wikis"
            echo "ℹ️ Skipping wiki sync (this is not an error)"
          fi
          
      - name: Sync documentation
        if: steps.wiki-check.outputs.wiki_exists == 'true'
        run: |
          # Copy docs to wiki, converting filenames for wiki format
          cp -r docs/* wiki/ 2>/dev/null || true
          
          # Wiki uses dashes instead of underscores in URLs
          cd wiki
          for file in *.MD *.md; do
            if [[ -f "$file" ]]; then
              # Convert underscores to dashes for better wiki URLs
              newname=$(echo "$file" | sed 's/_/-/g')
              if [[ "$file" != "$newname" ]]; then
                mv "$file" "$newname"
              fi
            fi
          done
          
          # Create/update Home page with index
          cat > Home.md << 'EOF'
          # nself Documentation Wiki

          Welcome to the nself wiki! This documentation is automatically synced from the `/docs` folder.

          ## Quick Links
          
          ### Getting Started
          - [[Troubleshooting|TROUBLESHOOTING]] - Common issues and solutions
          - [[Examples|EXAMPLES]] - Usage examples
          - [[Migration Guide|MIGRATION-0.2.x-to-0.3.0]] - Upgrading from v0.2.x

          ### Reference
          - [[API Reference|API]] - Complete command reference
          - [[Architecture|ARCHITECTURE]] - System design
          - [[Directory Structure|DIRECTORY-STRUCTURE]] - Project organization
          - [[Release Notes|RELEASES]] - Version history
          - [[Changelog|CHANGELOG]] - Recent changes

          ### Development
          - [[Contributing|CONTRIBUTING]] - How to contribute
          - [[Code Style|CODE-STYLE]] - Coding standards
          - [[Testing Strategy|TESTING-STRATEGY]] - Testing approach
          - [[Decisions|DECISIONS]] - Architectural decisions
          - [[Output Formatting|OUTPUT-FORMATTING]] - UI standards
          - [[Refactoring Roadmap|REFACTORING-ROADMAP]] - Future plans

          ## Latest Release

          **v0.3.0** - Major architectural refactor with modular src-centric design. [See release notes](https://github.com/acamarata/nself/releases/latest)

          ## For Contributors

          This wiki is automatically generated from `/docs`. To make changes:
          1. Edit files in the `/docs` folder
          2. Submit a PR to the main repository
          3. Wiki updates automatically on merge

          ## Support

          - [GitHub Issues](https://github.com/acamarata/nself/issues)
          - [Website](https://nself.org)
          - [Commercial Licensing](https://nself.org/commercial)
          EOF
          
      - name: Push to wiki
        if: steps.wiki-check.outputs.wiki_exists == 'true'
        run: |
          cd wiki
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Check current branch
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $BRANCH"
          
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Sync documentation from main repo"
            git push origin "$BRANCH"
          else
            echo "No changes to sync"
          fi